before:
  hooks:
    - go mod tidy
builds:
  - id: sunshine
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    main: cmd/sunshine/main.go
    binary: sunshine
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
archives:
  - format: zip
