package service

import (
	"math/rand"
	"text/template"
	"time"
)

func init() {
	var err error
	serviceLogicTmpl, err = template.New("serviceLogic").Parse(serviceLogicTmplRaw)
	if err != nil {
		panic(err)
	}
	routerTmpl, err = template.New("serviceRouter").Parse(routerTmplRaw)
	if err != nil {
		panic(err)
	}
	rpcErrCodeTmpl, err = template.New("rpcErrCode").Parse(rpcErrCodeTmplRaw)
	if err != nil {
		panic(err)
	}

	rand.Seed(time.Now().UnixNano()) //nolint
}

var (
	serviceLogicTmpl    *template.Template
	serviceLogicTmplRaw = `// Code generated by https://github.com/18721889353/sunshine

package service

import (
	"context"
{{if .HasWebSocketMethod}}
	"encoding/hex"
	"encoding/json"
	"google.golang.org/protobuf/proto"
{{end}}

	// import api service package here
	//"moduleNameExample/internal/rpcclient"
)

{{- range .PbServices}}

var _ {{.ProtoPkgName}}.{{.Name}}Logicer = (*{{.LowerName}}Client)(nil)

type {{.LowerName}}Client struct {
	// define rpc clients interface here
	// example:
	//	    {{.LowerName}}Cli {{.ProtoPkgName}}.{{.Name}}Client
}

// New{{.Name}}Client create a client
func New{{.Name}}Client() {{.ProtoPkgName}}.{{.Name}}Logicer {
	return &{{.LowerName}}Client{
		// example:
		//	    {{.LowerName}}Cli: {{.ProtoPkgName}}.New{{.Name}}Client(rpcclient.Get{{.CutServiceName}}RPCConn()),
	}
}

{{- range .Methods}}

{{if eq .InvokeType 0}}{{if .Path}}{{.Comment}}
func (c *{{.LowerServiceName}}Client) {{.MethodName}}(ctx context.Context, req *{{.RequestImportPkgName}}.{{.Request}}) (*{{.ReplyImportPkgName}}.{{.Reply}}, error) {
{{if .IsWebSocket}}
	// ========== 运行时自动检测 JSON / Binary 协议 ==========
	// JSON 文本消息 → json.Unmarshal + switch msg.Type
	// Binary protobuf 消息 → proto.Unmarshal + proto.Marshal

	wsCtx := context.WithoutCancel(ctx)

	client, ok := wsCtx.Value({{.RequestImportPkgName}}.WsConnKey).(*gows.Client)
	if !ok {
		return nil, ecode.StatusInternalServerError.Err()
	}

readLoop:
	for {
		message, readErr := client.ReadMsgFromClientReadCh(wsCtx)
		if readErr != nil {
			logger.WarnWithCtx(wsCtx, "ws read error", logger.Err(readErr))
			break
		}

		req := &{{.RequestImportPkgName}}.{{.Request}}{}

		// 尝试 JSON 反序列化，成功且含 Type 字段则为文本协议
		if err := json.Unmarshal(message, req); err == nil && req.Type != "" {
			// JSON 协议：按 type 字段路由分发
			switch req.Type {
			case "ping":
				if err := client.WriteJSONToClientWriteCh(wsCtx, gows.Message{Type: "pong"}); err != nil {
					logger.WarnWithCtx(wsCtx, "ws write pong error", logger.Err(err))
					break readLoop
				}
			default:
				// TODO: 处理业务逻辑
				// reply, err := c.{{.LowerServiceName}}Cli.{{.MethodName}}(wsCtx, &model.{{.ServiceName}}{...})
				if err := client.WriteJSONToClientWriteCh(wsCtx, gows.Message{Type: "reply", Data: req.Name}); err != nil {
					logger.WarnWithCtx(wsCtx, "ws write reply failed", logger.Err(err))
					break readLoop
				}
			}
		} else {
			// 不是 JSON，尝试 Binary protobuf
			if err := proto.Unmarshal(message, req); err != nil {
				logger.WarnWithCtx(wsCtx, "ws unmarshal failed", logger.Err(err))
				continue
			}
			logger.InfoWithCtx(wsCtx, "ws received binary", logger.String("msg", hex.EncodeToString(message)))

			// TODO: 处理业务逻辑

			reply := &{{.ReplyImportPkgName}}.{{.Reply}}{Message: "Hello, " + req.Name}
			data, _ := proto.Marshal(reply)
			if err := client.WriteRawToClientWriteCh(wsCtx, data); err != nil {
				logger.WarnWithCtx(wsCtx, "ws write raw failed", logger.Err(err))
				break
			}
		}
	}

	//
	// ========== 在读写循环外，通过 Client 的 Dispatcher 代理向指定用户推送消息 ==========
	// 适用于其他 HTTP/gRPC 接口中触发的推送（此处仅作示例，不在读写循环内执行）
	//
	// 向单个用户发送:
	//	client.SendToUIDCtx(wsCtx, "target_uid", gows.Message{Type: "notify", Msg: "你有新消息"})
	//
	// 向多个用户发送:
	//	client.SendToMultiUIDCtx(wsCtx, []string{"uid1", "uid2"}, gows.Message{Type: "batch", Data: map[string]any{"scores": scores}})
	//
	// 向所有在线用户广播:
	//	client.BroadcastCtx(wsCtx, gows.Message{Type: "announcement", Msg: "系统维护通知"})
	//
	// 向所有在线用户可靠广播（转为按 UID 下发，支持离线积压）:
	//	client.BroadcastReliableCtx(wsCtx, gows.Message{Type: "announcement", Msg: "重要通知"})
	//
	// 注意: 分布式模式下（enableDistributed=true），以上调用会自动跨实例投递。
	// 单机模式下同样可用，无需关心底层是否为分布式 Backend。

	// ========== 读写循环结束 ==========
		return nil, errcode.SkipResponse
{{else}}
	panic("{{.Prompt}}")

	// fill in the business logic code here
	// example:
	//	    {{if .IsIgnoreShouldBind}}gc, ctx := middleware.AdaptCtx(ctx)
	//	    if err = gc.ShouldBindJSON(req); err != nil {
	//	    	logger.WarnWithCtx(ctx, "ShouldBindJSON error", logger.Err(err))
	//	    	return nil, ecode.StatusInvalidParams.Err()
	//	    }{{else}}{{if .IsPassGinContext}}gc, ctx := middleware.AdaptCtx(ctx){{end}}{{end}}
	//	    err := req.Validate()
	//	    if err != nil {
	//		    logger.WarnWithCtx(ctx, "req.Validate error", logger.Err(err), logger.Any("req", req))
	//		    return nil, ecode.StatusInvalidParams.Err()
	//	    }
	//
	//	    reply, err := c.{{.LowerServiceName}}Cli.{{.MethodName}}(ctx, &{{.RequestImportPkgName}}.{{.Request}}{
{{- range .RequestFields}}
	//     	{{.Name}}: req.{{.Name}},
{{- end}}
	//     })
	//	    if err != nil {
	//     	logger.WarnWithCtx(ctx, "{{.MethodName}} error", logger.Err(err))
	//     	return nil, err
	//     }
	//
	//     return &{{.ReplyImportPkgName}}.{{.Reply}}{
{{- range .ReplyFields}}
	//     	{{.Name}}: reply.{{.Name}},
{{- end}}
	//     }, nil
{{end}}}{{end}}{{end}}

{{- end}}

// ---------- Do not delete or move this split line, this is the merge code marker ----------

{{- end}}
`

	routerTmpl    *template.Template
	routerTmplRaw = `// Code generated by https://github.com/18721889353/sunshine

package routers

import (
	"context"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc/metadata"

	"github.com/18721889353/sunshine/pkg/gin/middleware"
	"github.com/18721889353/sunshine/pkg/logger"

	// import api service package here
	"moduleNameExample/internal/service"
)

func init() {
	allMiddlewareFns = append(allMiddlewareFns, func(c *middlewareConfig) {
{{- range .PbServices}}
		{{.LowerName}}Middlewares(c)
{{- end}}
	})

	allRouteFns = append(allRouteFns,
		func(r *gin.Engine, groupPathMiddlewares map[string][]gin.HandlerFunc, singlePathMiddlewares map[string][]gin.HandlerFunc) {
{{- range .PbServices}}
			{{.LowerName}}Router(r, groupPathMiddlewares, singlePathMiddlewares, service.New{{.Name}}Client())
{{- end}}
		})
}

{{- range .PbServices}}

func {{.LowerName}}Router(
	r *gin.Engine,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iService {{.ProtoPkgName}}.{{.Name}}Logicer) {
	ctxFn := func(c *gin.Context) context.Context {
		md := metadata.New(map[string]string{
			"uid":                             c.GetString("uid"),
			"agent":                           c.Request.UserAgent(),
			string(logger.ContextKeyRequestID): middleware.GCtxRequestID(c),                    // request_id
			"clientIP":                        c.ClientIP(),                                   //在这里获取client ip
			middleware.HeaderAuthorizationKey: c.GetHeader(middleware.HeaderAuthorizationKey), // authorization
		})
		return metadata.NewIncomingContext(c.Request.Context(), md)
	}

	{{.ProtoPkgName}}.Register{{.Name}}Router(
		r,
		groupPathMiddlewares,
		singlePathMiddlewares,
		iService,
		{{.ProtoPkgName}}.With{{.Name}}RPCResponse(),
		{{.ProtoPkgName}}.With{{.Name}}WrapCtx(ctxFn),
		{{.ProtoPkgName}}.With{{.Name}}RPCStatusToHTTPCode(
			// Set some error codes to standard http return codes,
			// by default there is already ecode.StatusInternalServerError and ecode.StatusServiceUnavailable
			// example:
			// 	ecode.StatusUnimplemented, ecode.StatusAborted,
		),
	)
}

// you can set the middleware of a route group, or set the middleware of a single route, 
// or you can mix them, pay attention to the duplication of middleware when mixing them, 
// it is recommended to set the middleware of a single route in preference
func {{.LowerName}}Middlewares(c *middlewareConfig) {
	// set up group route middleware, group path is left prefix rules,
	// if the left prefix is hit, the middleware will take effect, e.g. group route is /api/v1, route /api/v1/{{.LowerName}}/:id  will take effect
	//c.setGroupPath("/api/v1/{{.LowerName}}", middleware.Auth(middleware.WithSwitchHTTPCode(), middleware.WithJwtIgnoreMethods(config.Get().Jwt.IgnoreMethods.HTTP...)))

	// set up single route middleware, just uncomment the code and fill in the middlewares, nothing else needs to be changed
{{- range .Methods}}
	{{if eq .InvokeType 0}}{{if .Path}}//c.setSinglePath("{{.Method}}", "{{.Path}}", middleware.Auth())    {{.Comment}}{{end}}{{end}}
{{- end}}
}

// ---------- Do not delete or move this split line, this is the merge code marker ----------

{{- end}}
`

	rpcErrCodeTmpl *template.Template
	//nolint
	rpcErrCodeTmplRaw = `// Code generated by https://github.com/18721889353/sunshine

package ecode

import (
	"github.com/18721889353/sunshine/pkg/errcode"
)

{{- range .PbServices}}

// {{.LowerName}} business-level rpc error codes.
// the {{.LowerName}}NO value range is 1~100, if the same error code is used, it will cause panic.
var (
	_{{.LowerName}}NO       = {{.RandNumber}}
	_{{.LowerName}}Name     = "{{.LowerName}}"
	_{{.LowerName}}BaseCode = errcode.RCode(_{{.LowerName}}NO)
// --blank line--
{{- range $i, $v := .Methods}}
	{{if eq .InvokeType 0}}{{if .Path}}Status{{.MethodName}}{{.ServiceName}}   = errcode.NewRPCStatus(_{{.LowerServiceName}}BaseCode+{{$v.AddOne $i}}, "failed to {{.MethodName}} "+_{{.LowerServiceName}}Name){{end}}{{end}}
{{- end}}

	// error codes are globally unique, adding 1 to the previous error code
)

// ---------- Do not delete or move this split line, this is the merge code marker ----------

{{- end}}
`
)
