package router

import (
	"text/template"
)

func init() {
	var err error
	importPkgTmpl, err = template.New("importPkg").Parse(importPkgTmplRaw)
	if err != nil {
		panic(err)
	}
	ginRouterTmpl, err = template.New("ginRouter").Parse(ginRouterTmplRaw)
	if err != nil {
		panic(err)
	}
}

var (
	importPkgTmpl    *template.Template
	importPkgTmplRaw = `// Code generated by https://github.com/18721889353/sunshine, DO NOT EDIT.

package {{$.PackageName}}

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/18721889353/sunshine/pkg/errcode"
	"github.com/18721889353/sunshine/pkg/gin/middleware"
	"github.com/18721889353/sunshine/pkg/logger"

	{{if $.HasWebSocket}}"github.com/18721889353/sunshine/pkg/gows"
	{{end}}{{$.PackagePaths}}
)

{{if $.HasWebSocket}}
// WsConnKey 用于在 context 中存储 WebSocket 连接。
var WsConnKey = "ws_conn"

// WsTokenKey 用于在 context 中存储 WebSocket token（从 query 参数获取）。
var WsTokenKey = "ws_token"
{{end}}
`

	ginRouterTmpl    *template.Template
	ginRouterTmplRaw = `
type {{$.Name}}Logicer interface {
{{- range $.UniqueMethods}}
	{{if eq .InvokeType 0}}{{if .Path}}{{.Name}}(ctx context.Context, req *{{.RequestImportPkgName}}{{.Request}}) (*{{.ReplyImportPkgName}}{{.Reply}}, error){{end}}{{end}}
{{- end}}
}

type {{$.Name}}Option func(*{{$.LowerName}}Options)

type {{$.LowerName}}Options struct {
	isFromRPC bool
	isMessage bool
	responser errcode.Responser
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *{{$.LowerName}}Options) apply(opts ...{{$.Name}}Option) {
	for _, opt := range opts {
		opt(o)
	}
}

func With{{$.Name}}HTTPResponse() {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.isFromRPC = false
	}
}

func With{{$.Name}}RPCResponse() {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.isFromRPC = true
	}
}

func With{{$.Name}}Message() {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.isMessage = true
	}
}

func With{{$.Name}}Responser(responser errcode.Responser) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.responser = responser
	}
}

func With{{$.Name}}ErrorToHTTPCode(e ...*errcode.Error) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.httpErrors = e
	}
}

func With{{$.Name}}RPCStatusToHTTPCode(s ...*errcode.RPCStatus) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.rpcStatus = s
	}
}

func With{{$.Name}}WrapCtx(wrapCtxFn func(c *gin.Context) context.Context) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func Register{{$.Name}}Router(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic {{$.Name}}Logicer,
	opts ...{{$.Name}}Option) {

	o := &{{$.LowerName}}Options{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isMessage,o.isFromRPC, o.httpErrors, o.rpcStatus)
	}

	r := &{{$.LowerName}}Router {
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type {{$.LowerName}}Router struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                {{$.Name}}Logicer
	iResponse             errcode.Responser
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *{{$.LowerName}}Router) register() {
{{range .Methods}}	{{if eq .InvokeType 0}}{{if .Path}}r.iRouter.Handle("{{.Method}}", "{{.Path}}", r.withMiddleware("{{.Method}}", "{{.Path}}", r.{{ .HandlerName }})...){{end}}{{end}}
{{end}}
}

func (r *{{$.LowerName}}Router) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

{{range .Methods}}
{{if eq .InvokeType 0}}{{if .Path}}
{{if .IsWebSocket}}func (r *{{$.LowerName}}Router) {{ .HandlerName }} (c *gin.Context) {
	// 应用 wrapCtxFn 注入 gRPC metadata（含 request_id），与普通 HTTP 路径保持一致
	 ctx := c.Request.Context()
	 if r.wrapCtxFn != nil {
		 ctx = r.wrapCtxFn(c)
	 } else {
		 ctx = middleware.WrapCtx(c)
	 }

	 // ========== router 层解析 JWT，提取 UID，传入 Client ==========
	 uid := ""
	 if token := c.Request.URL.Query().Get("token"); token != "" {
		 if parsedUID, parseErr := gows.ParseTokenCtx(ctx, token); parseErr == nil {
			 uid = parsedUID
		 }
	 }

	 client, err := gows.Upgrade(c, gows.WithHeartbeat(), gows.WithClientUID(uid), gows.WithDispatcher(gows.DefaultDispatcher))
	 if err != nil {
		 logger.WarnWithCtx(ctx, "websocket upgrade error", logger.Err(err), middleware.GCtxRequestIDField(c))
		 return
	 }
	 defer client.Close()

	 ctx = context.WithValue(ctx, WsConnKey, client)
	 _, err = r.iLogic.{{.Name}}(ctx, &{{.RequestImportPkgName}}{{.Request}}{})
	 if err != nil {
		 if errors.Is(err, errcode.SkipResponse) {
			 return
		 }
		 logger.WarnWithCtx(ctx, "websocket logic error", logger.Err(err))
		 return
	 }
}
{{else}}func (r *{{$.LowerName}}Router) {{ .HandlerName }} (c *gin.Context) {
	req := &{{.RequestImportPkgName}}{{.Request}}{}
{{if eq .IsIgnoreShouldBind false}}	var err error
{{if .HasPathParams }}
	if err = c.ShouldBindUri(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBindUri error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{end}}

{{if eq .Method "GET" "DELETE" }}
	if err = c.ShouldBindQuery(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBindQuery error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{else if eq .Method "POST" "PUT" "PATCH"}}
	if err = c.ShouldBindJSON(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBindJSON error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{else}}
	if err = c.ShouldBind(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBind error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{end}}
{{end}}

{{if .IsPassGinContext}}
	var ctx context.Context = c
{{else}}
	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}
{{end}}

	out, err := r.iLogic.{{.Name}}(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

{{if not .IsWebSocket}}	r.iResponse.Success(c, out)
{{end}}
}{{end}}{{end}}{{end}}{{end}}
`
)
