package router

import (
	"text/template"
)

func init() {
	var err error
	importPkgTmpl, err = template.New("importPkg").Parse(importPkgTmplRaw)
	if err != nil {
		panic(err)
	}
	ginRouterTmpl, err = template.New("ginRouter").Parse(ginRouterTmplRaw)
	if err != nil {
		panic(err)
	}
}

var (
	importPkgTmpl    *template.Template
	importPkgTmplRaw = `// Code generated by https://github.com/18721889353/sunshine, DO NOT EDIT.

package {{$.PackageName}}

import (
	"context"
	"errors"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/18721889353/sunshine/pkg/errcode"
	"github.com/18721889353/sunshine/pkg/gin/middleware"
	"github.com/18721889353/sunshine/pkg/logger"

	{{if $.HasWebSocket}}
	"net/http"
	"sync"
	"time"
	"{{.ModuleName}}/internal/config"
	"github.com/18721889353/sunshine/pkg/gows"
	{{end}}{{$.PackagePaths}}
)

{{if $.HasWebSocket}}
// WsConnKey 用于在 context 中存储 WebSocket 连接。
var WsConnKey = "ws_conn"

// WsTokenKey 用于在 context 中存储 WebSocket token（从 query 参数获取）。
var WsTokenKey = "ws_token"

// wsBackendOnce 确保分布式 Dispatcher 只初始化一次。
var wsBackendOnce sync.Once

// wsDispatcher 分布式 Dispatcher 实例，由 initWSDispatcher 惰性创建。
// 仅在 EnableDistributed=true 时非 nil，供 Upgrade 注册使用。
// 不覆盖 gows.DefaultDispatcher，保持单机模式默认实例不受影响。
var wsDispatcher *gows.DistributedDispatcher

// initWSDispatcher 初始化分布式 Dispatcher。
// 当 config.Get().Websocket.Distributed.EnableDistributed=true 时，使用 RabbitMQ 作为 Backend
// 创建分布式 Dispatcher 实例，支持跨实例消息分发。
// 将实例存入 wsDispatcher 供 Upgrade 使用，不修改 gows.DefaultDispatcher。
func initWSDispatcher() {
	wsBackendOnce.Do(func() {
		if !config.Get().Websocket.Distributed.EnableDistributed {
			return
		}
		backend := gows.NewRabbitMQBackend(
			config.Get().Websocket.Distributed.RabbitmqURL,
			config.Get().Websocket.Distributed.Exchange,
		)
		dd := gows.NewDispatcher(backend,
			gows.WithWorkerPool(config.Get().Websocket.Distributed.WorkerPool),
			gows.WithMaxConnections(config.Get().Websocket.Distributed.MaxConnections),
		)
		wsDispatcher = dd
		dd.Start(context.Background())
	})
}
{{end}}
`

	ginRouterTmpl    *template.Template
	ginRouterTmplRaw = `
type {{$.Name}}Logicer interface {
{{- range $.UniqueMethods}}
	{{if eq .InvokeType 0}}{{if .Path}}{{.Name}}(ctx context.Context, req *{{.RequestImportPkgName}}{{.Request}}) (*{{.ReplyImportPkgName}}{{.Reply}}, error){{end}}{{end}}
{{- end}}
}

type {{$.Name}}Option func(*{{$.LowerName}}Options)

type {{$.LowerName}}Options struct {
	isFromRPC bool
	isMessage bool
	responser errcode.Responser
	httpErrors []*errcode.Error
	rpcStatus  []*errcode.RPCStatus
	wrapCtxFn  func(c *gin.Context) context.Context
}

func (o *{{$.LowerName}}Options) apply(opts ...{{$.Name}}Option) {
	for _, opt := range opts {
		opt(o)
	}
}

func With{{$.Name}}HTTPResponse() {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.isFromRPC = false
	}
}

func With{{$.Name}}RPCResponse() {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.isFromRPC = true
	}
}

func With{{$.Name}}Message() {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.isMessage = true
	}
}

func With{{$.Name}}Responser(responser errcode.Responser) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.responser = responser
	}
}

func With{{$.Name}}ErrorToHTTPCode(e ...*errcode.Error) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.httpErrors = e
	}
}

func With{{$.Name}}RPCStatusToHTTPCode(s ...*errcode.RPCStatus) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.rpcStatus = s
	}
}

func With{{$.Name}}WrapCtx(wrapCtxFn func(c *gin.Context) context.Context) {{$.Name}}Option {
	return func(o *{{$.LowerName}}Options) {
		o.wrapCtxFn = wrapCtxFn
	}
}

func Register{{$.Name}}Router(
	iRouter gin.IRouter,
	groupPathMiddlewares map[string][]gin.HandlerFunc,
	singlePathMiddlewares map[string][]gin.HandlerFunc,
	iLogic {{$.Name}}Logicer,
	opts ...{{$.Name}}Option) {

	o := &{{$.LowerName}}Options{}
	o.apply(opts...)

	if o.responser == nil {
		o.responser = errcode.NewResponser(o.isMessage,o.isFromRPC, o.httpErrors, o.rpcStatus)
	}

	// 初始化 WebSocket 分布式 Dispatcher（如启用）
	initWSDispatcher()

	r := &{{$.LowerName}}Router {
		iRouter:               iRouter,
		groupPathMiddlewares:  groupPathMiddlewares,
		singlePathMiddlewares: singlePathMiddlewares,
		iLogic:                iLogic,
		iResponse:             o.responser,
		wrapCtxFn:             o.wrapCtxFn,
	}
	r.register()
}

type {{$.LowerName}}Router struct {
	iRouter               gin.IRouter
	groupPathMiddlewares  map[string][]gin.HandlerFunc
	singlePathMiddlewares map[string][]gin.HandlerFunc
	iLogic                {{$.Name}}Logicer
	iResponse             errcode.Responser
	wrapCtxFn             func(c *gin.Context) context.Context
}

func (r *{{$.LowerName}}Router) register() {
{{range .Methods}}	{{if eq .InvokeType 0}}{{if .Path}}r.iRouter.Handle("{{.Method}}", "{{.Path}}", r.withMiddleware("{{.Method}}", "{{.Path}}", r.{{ .HandlerName }})...){{end}}{{end}}
{{end}}
}

func (r *{{$.LowerName}}Router) withMiddleware(method string, path string, fn gin.HandlerFunc) []gin.HandlerFunc {
	handlerFns := []gin.HandlerFunc{}

	// determine if a route group is hit or miss, left prefix rule
	for groupPath, fns := range r.groupPathMiddlewares {
		if groupPath == "" || groupPath == "/" {
			handlerFns = append(handlerFns, fns...)
			continue
		}
		size := len(groupPath)
		if len(path) < size {
			continue
		}
		if groupPath == path[:size] {
			handlerFns = append(handlerFns, fns...)
		}
	}

	// determine if a single route has been hit
	key := strings.ToUpper(method) + "->" + path
	if fns, ok := r.singlePathMiddlewares[key]; ok {
		handlerFns = append(handlerFns, fns...)
	}

	return append(handlerFns, fn)
}

{{range .Methods}}
{{if eq .InvokeType 0}}{{if .Path}}
{{if .IsWebSocket}}func (r *{{$.LowerName}}Router) {{ .HandlerName }} (c *gin.Context) {
	// 应用 wrapCtxFn 注入 gRPC metadata（含 request_id），与普通 HTTP 路径保持一致
	ctx := c.Request.Context()
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}

	// ========== router 层解析 JWT，提取 UID，传入 Client ==========
	token := c.Request.URL.Query().Get("token")
	if token == "" {
		logger.WarnWithCtx(ctx, "websocket missing token")
		return
	}
	uid, err := gows.ParseTokenCtx(ctx, token)
	if err != nil {
		logger.WarnWithCtx(ctx, "websocket parse token error", logger.Err(err))
		return
	}
	if uid == "" {
		logger.WarnWithCtx(ctx, "websocket parse token empty uid")
		return
	}

	// ========== 构建 WebSocket 升级选项（全部从配置读取，0=不限制/默认值） ==========
	// CORS: 默认拒绝所有来源，生产环境请根据实际域名限制。
	// 限流/单 IP 限制从 config.Get().Websocket 读取。
	// 分布式模式（enableDistributed=true）时自动注册到 DefaultDispatcher。
	//
	// 完整配置字段映射（configs/serverNameExample.yml → option）：
	//
	// 【CORS & 连接基础】
	//   .Websocket.Cors.Cors             → gows.WithCheckOrigin()           CORS 开关
	//   .Websocket.Cors.ReadBufferSize    → gows.WithBufferSize(read, 0)     读缓冲区大小（字节）
	//   .Websocket.Cors.WriteBufferSize   → gows.WithBufferSize(0, write)    写缓冲区大小（字节）
	//   .Websocket.Cors.EnableCompression → gows.WithEnableCompression()     WebSocket 压缩开关
	//   .Websocket.Cors.Subprotocols      → gows.WithSubprotocols()          子协议列表（逗号分隔）
	//
	// 【限流与安全防护】
	//   .Websocket.Limit.RateLimitRps      → gows.WithWsRateLimit(rps, burst)   全局升级速率（每秒请求数）
	//   .Websocket.Limit.RateLimitBurst    → gows.WithWsRateLimit(rps, burst)   限流突发量
	//   .Websocket.Limit.MaxConnPerIP      → gows.WithMaxConnPerIP()          单 IP 最大连接数
	//   .Websocket.Limit.ReadLimit         → gows.WithReadLimit()             单条消息读取大小限制（字节）
	//   .Websocket.Limit.WriteLimit        → gows.WithWriteLimit()            单条消息写入大小限制（字节）
	//
	// 【超时控制】
	//   .Websocket.Timeout.ReadTimeout       → gows.WithReadTimeout()           读取超时（秒），0=不限制
	//   .Websocket.Timeout.WriteTimeout      → gows.WithWriteTimeout()          写入超时（秒），0=默认10s
	//
	// 【心跳保活】
	//   .Websocket.Heartbeat.HeartbeatInterval → gows.WithHeartbeatInterval()     心跳间隔（秒）
	//   .Websocket.Heartbeat.PongTimeout       → gows.WithPongTimeout()           Pong 响应超时（秒）
	//   .Websocket.Heartbeat.PingWriteWait     → gows.WithPingWriteWait()         Ping 控制帧写入超时（秒）
	//
	// 【客户端队列】
	//   .Websocket.Queue.WriteQueueSize    → gows.WithQueueSize(write, read)  写入队列容量
	//   .Websocket.Queue.ReadQueueSize     → gows.WithQueueSize(write, read)  读取队列容量
	//
	// 【单点登录】
	//   .Websocket.SSO.EnableSSO           → gows.WithSSO()                   后登录踢前登录
	upgradeOpts := []gows.UpgradeOption{
		// CORS: cors=false 拒绝所有来源；cors=true 时检查 allowedOrigins 白名单
		//   allowedOrigins 为空列表时允许所有来源（向后兼容）
		gows.WithCheckOrigin(func(r *http.Request) bool {
			if !config.Get().Websocket.Cors.Cors {
				return false
			}
			origins := config.Get().Websocket.Cors.AllowedOrigins
			if len(origins) == 0 {
				return true
			}
			origin := r.Header.Get("Origin")
			for _, allowed := range origins {
				if allowed == origin || allowed == "*" {
					return true
				}
			}
			return false
		}),
		// 心跳保活：从配置读取间隔、Pong 超时、Ping 写入超时（秒），0=使用默认值
		// enableHeartbeat=true 时添加 WithHeartbeatOptions，否则不启用心跳
		// 用户标识：从 JWT 解析的 uid 传入 Client，用于链路追踪
		gows.WithClientUID(uid),
		// 读写缓冲区大小（字节），0=使用 gorilla/websocket 默认值 4096
		gows.WithBufferSize(config.Get().Websocket.Cors.ReadBufferSize, config.Get().Websocket.Cors.WriteBufferSize),
		// 单 IP 连接数上限，0=不限制
		gows.WithMaxConnPerIP(config.Get().Websocket.Limit.MaxConnPerIP),
		// 读取超时：readLoop 在超时后返回错误，0=不限制（由心跳间接管理）
		gows.WithReadTimeout(time.Duration(config.Get().Websocket.Timeout.ReadTimeout) * time.Second),
		// 写入超时：writeWithRetry 在超时后重试，0=默认 10s
		gows.WithWriteTimeout(time.Duration(config.Get().Websocket.Timeout.WriteTimeout) * time.Second),
		// 单条消息读取大小限制（字节），0=不限制
		gows.WithReadLimit(int64(config.Get().Websocket.Limit.ReadLimit)),
		// 单条消息写入大小限制（字节），0=不限制
		gows.WithWriteLimit(int64(config.Get().Websocket.Limit.WriteLimit)),
		// WebSocket 压缩开关：true=启用（默认），false=禁用
		gows.WithEnableCompression(config.Get().Websocket.Cors.EnableCompression),
		// 子协议列表：从逗号分隔字符串解析，空字符串表示不协商
		gows.WithSubprotocols(strings.Split(config.Get().Websocket.Cors.Subprotocols, ",")...),
		// 客户端读写队列容量（0=默认 64），控制背压行为
		gows.WithQueueSize(config.Get().Websocket.Queue.WriteQueueSize, config.Get().Websocket.Queue.ReadQueueSize),
	}
	// 条件启用心跳（根据 enableHeartbeat 配置）
	if config.Get().Websocket.Heartbeat.EnableHeartbeat {
		upgradeOpts = append(upgradeOpts, gows.WithHeartbeatOptions(
			gows.WithHeartbeatInterval(time.Duration(config.Get().Websocket.Heartbeat.HeartbeatInterval)*time.Second),
			gows.WithPongTimeout(time.Duration(config.Get().Websocket.Heartbeat.PongTimeout)*time.Second),
			gows.WithPingWriteWait(time.Duration(config.Get().Websocket.Heartbeat.PingWriteWait)*time.Second),
		))
	}
	// 条件启用全局限流（根据 enableRateLimit 配置）
	if config.Get().Websocket.Limit.EnableRateLimit {
		upgradeOpts = append(upgradeOpts,
			gows.WithWsRateLimit(config.Get().Websocket.Limit.RateLimitRps, config.Get().Websocket.Limit.RateLimitBurst),
		)
	}
	if config.Get().Websocket.Distributed.EnableDistributed {
		upgradeOpts = append(upgradeOpts, gows.WithEnableDistributed(true), gows.WithDispatcher(wsDispatcher))
	}
	// 条件启用单点登录（根据 enableSSO 配置）
	if config.Get().Websocket.Sso.EnableSSO {
		upgradeOpts = append(upgradeOpts, gows.WithSSO())
	}
	client, err := gows.Upgrade(c, upgradeOpts...)
	if err != nil {
		logger.WarnWithCtx(ctx, "websocket upgrade error", logger.Err(err), middleware.GCtxRequestIDField(c))
		return
	}
	defer client.Close()

	ctx = context.WithValue(ctx, WsConnKey, client)
	_, err = r.iLogic.{{.Name}}(ctx, &{{.RequestImportPkgName}}{{.Request}}{})
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		logger.WarnWithCtx(ctx, "websocket logic error", logger.Err(err))
		return
	}
}
{{else}}func (r *{{$.LowerName}}Router) {{ .HandlerName }} (c *gin.Context) {
	req := &{{.RequestImportPkgName}}{{.Request}}{}
{{if eq .IsIgnoreShouldBind false}}	var err error
{{if .HasPathParams }}
	if err = c.ShouldBindUri(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBindUri error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{end}}

{{if eq .Method "GET" "DELETE" }}
	if err = c.ShouldBindQuery(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBindQuery error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{else if eq .Method "POST" "PUT" "PATCH"}}
	if err = c.ShouldBindJSON(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBindJSON error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{else}}
	if err = c.ShouldBind(req); err != nil {
		logger.WarnWithCtx(c.Request.Context(), "ShouldBind error", logger.Err(err), middleware.GCtxRequestIDField(c))
		r.iResponse.ParamError(c, err)
		return
	}
{{end}}
{{end}}

{{if .IsPassGinContext}}
	var ctx context.Context = c
{{else}}
	var ctx context.Context
	if r.wrapCtxFn != nil {
		ctx = r.wrapCtxFn(c)
	} else {
		ctx = middleware.WrapCtx(c)
	}
{{end}}

	out, err := r.iLogic.{{.Name}}(ctx, req)
	if err != nil {
		if errors.Is(err, errcode.SkipResponse) {
			return
		}
		r.iResponse.Error(c, err)
		return
	}

{{if not .IsWebSocket}}	r.iResponse.Success(c, out)
{{end}}
}{{end}}{{end}}{{end}}{{end}}
`
)
