package gozip

import (
	"fmt"
	"github.com/yeka/zip"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestZipFilesFromPaths 测试从文件路径列表创建ZIP（带密码）
func TestZipFilesFromPaths(t *testing.T) {
	// 创建临时测试目录
	tempDir := t.TempDir()

	// 创建测试文件
	testFiles := createTestFiles(t, tempDir, 3)

	// 测试1: 带密码压缩
	t.Run("WithPassword", func(t *testing.T) {
		destPath := filepath.Join(tempDir, "test_with_password.zip")
		result, err := ZipFilesFromPaths(testFiles, destPath, "password123")

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result == nil {
			t.Fatal("结果不应为nil")
		}

		if result.Path != destPath {
			t.Errorf("期望路径 %s, 实际 %s", destPath, result.Path)
		}

		if result.FileCount != 3 {
			t.Errorf("期望文件数 3, 实际 %d", result.FileCount)
		}

		if !result.IsEncrypted {
			t.Error("应该已加密")
		}

		if result.Size <= 0 {
			t.Error("文件大小应大于0")
		}

		// 验证文件确实存在
		if _, statErr := os.Stat(destPath); statErr != nil {
			t.Errorf("压缩文件不存在: %v", statErr)
		}
	})

	// 测试2: 不带密码压缩
	t.Run("WithoutPassword", func(t *testing.T) {
		destPath := filepath.Join(tempDir, "test_without_password.zip")
		result, err := ZipFilesFromPaths(testFiles, destPath, "")

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.IsEncrypted {
			t.Error("不应该加密")
		}
	})

	// 测试3: 空文件列表
	t.Run("EmptyFileList", func(t *testing.T) {
		_, err := ZipFilesFromPaths([]string{}, "", "password")
		if err == nil {
			t.Error("空文件列表应该返回错误")
		}
	})

	// 测试4: 不存在的文件
	t.Run("NonExistentFile", func(t *testing.T) {
		_, err := ZipFilesFromPaths([]string{"/nonexistent/file.txt"}, "", "password")
		if err == nil {
			t.Error("不存在的文件应该返回错误")
		}
	})

	// 测试5: 自动生成目标路径
	t.Run("AutoGenerateDestPath", func(t *testing.T) {
		result, err := ZipFilesFromPaths(testFiles, "", "password123")

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.Path == "" {
			t.Error("自动生成的路径不应为空")
		}

		// 验证文件确实存在
		if _, statErr := os.Stat(result.Path); statErr != nil {
			t.Errorf("自动生成的压缩文件不存在: %v", statErr)
		}

		// 清理自动生成的文件
		defer os.Remove(result.Path)
	})

	// 测试6: 大量文件压缩
	t.Run("ManyFiles", func(t *testing.T) {
		manyFiles := createTestFiles(t, tempDir, 10)
		destPath := filepath.Join(tempDir, "test_many_files.zip")
		result, err := ZipFilesFromPaths(manyFiles, destPath, "password")

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.FileCount != 10 {
			t.Errorf("期望文件数 10, 实际 %d", result.FileCount)
		}
	})
}

// TestZipFilesFromPathsWithOptions 测试自定义选项压缩
func TestZipFilesFromPathsWithOptions(t *testing.T) {
	tempDir := t.TempDir()
	testFiles := createTestFiles(t, tempDir, 2)

	t.Run("CustomOptions", func(t *testing.T) {
		options := &ZipOptions{
			Password:    "test123",
			Encryption:  ZipAES128Encryption,
			Compression: ZipBestCompression,
		}

		destPath := filepath.Join(tempDir, "test_custom_options.zip")
		result, err := ZipFilesFromPathsWithOptions(testFiles, destPath, options)

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if !result.IsEncrypted {
			t.Error("应该已加密")
		}
	})

	t.Run("NilOptions", func(t *testing.T) {
		destPath := filepath.Join(tempDir, "test_nil_options.zip")
		result, err := ZipFilesFromPathsWithOptions(testFiles, destPath, nil)

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.FileCount != 2 {
			t.Errorf("期望文件数 2, 实际 %d", result.FileCount)
		}
	})

	t.Run("StandardEncryption", func(t *testing.T) {
		options := &ZipOptions{
			Password:   "test123",
			Encryption: ZipStandardEncryption,
		}

		destPath := filepath.Join(tempDir, "test_standard_enc.zip")
		result, err := ZipFilesFromPathsWithOptions(testFiles, destPath, options)

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if !result.IsEncrypted {
			t.Error("应该已加密")
		}
	})

	t.Run("BestCompression", func(t *testing.T) {
		options := &ZipOptions{
			Password:    "test123",
			Compression: ZipBestCompression,
		}

		destPath := filepath.Join(tempDir, "test_best_compression.zip")
		result, err := ZipFilesFromPathsWithOptions(testFiles, destPath, options)

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.Size <= 0 {
			t.Error("文件大小应大于0")
		}
	})

	t.Run("NoCompression", func(t *testing.T) {
		options := &ZipOptions{
			Compression: ZipNoCompression,
		}

		destPath := filepath.Join(tempDir, "test_no_compression.zip")
		result, err := ZipFilesFromPathsWithOptions(testFiles, destPath, options)

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.IsEncrypted {
			t.Error("不应该加密")
		}
	})
}

// TestZipDirectory 测试压缩整个目录
func TestZipDirectory(t *testing.T) {
	tempDir := t.TempDir()

	// 创建测试目录结构
	testDir := filepath.Join(tempDir, "test_source_dir")
	if err := os.MkdirAll(testDir, 0755); err != nil {
		t.Fatalf("创建测试目录失败: %v", err)
	}

	// 创建子目录
	subDir := filepath.Join(testDir, "subdir")
	if err := os.MkdirAll(subDir, 0755); err != nil {
		t.Fatalf("创建子目录失败: %v", err)
	}

	// 创建测试文件
	createTestFile(t, testDir, "file1.txt", "content1")
	createTestFile(t, testDir, "file2.txt", "content2")
	createTestFile(t, subDir, "file3.txt", "content3")

	t.Run("CompressDirectory", func(t *testing.T) {
		destPath := filepath.Join(tempDir, "test_directory.zip")
		result, err := ZipDirectory(testDir, destPath, "password123")

		if err != nil {
			t.Fatalf("压缩目录失败: %v", err)
		}

		if result.FileCount != 3 {
			t.Errorf("期望文件数 3, 实际 %d", result.FileCount)
		}

		if !result.IsEncrypted {
			t.Error("应该已加密")
		}
	})

	t.Run("EmptyDirectory", func(t *testing.T) {
		emptyDir := filepath.Join(tempDir, "empty_dir")
		if err := os.MkdirAll(emptyDir, 0755); err != nil {
			t.Fatalf("创建空目录失败: %v", err)
		}

		_, err := ZipDirectory(emptyDir, "", "password")
		if err == nil {
			t.Error("空目录应该返回错误")
		}
	})

	t.Run("NonExistentDirectory", func(t *testing.T) {
		_, err := ZipDirectory("/nonexistent/dir", "", "password")
		if err == nil {
			t.Error("不存在的目录应该返回错误")
		}
	})

	t.Run("FileNotDirectory", func(t *testing.T) {
		testFile := createTestFile(t, tempDir, "notadir.txt", "content")
		_, err := ZipDirectory(testFile, "", "password")
		if err == nil {
			t.Error("文件路径应该返回错误")
		}
	})
}

// TestZipDirectoryWithOptions 测试带选项的目录压缩
func TestZipDirectoryWithOptions(t *testing.T) {
	tempDir := t.TempDir()

	// 创建测试目录
	testDir := filepath.Join(tempDir, "test_dir")
	if err := os.MkdirAll(testDir, 0755); err != nil {
		t.Fatalf("创建测试目录失败: %v", err)
	}
	createTestFile(t, testDir, "file1.txt", "content1")
	createTestFile(t, testDir, "file2.txt", "content2")

	t.Run("CustomOptions", func(t *testing.T) {
		options := &ZipOptions{
			Password:   "dir_password",
			Encryption: ZipAES256Encryption,
		}

		destPath := filepath.Join(tempDir, "test_dir_custom.zip")
		result, err := ZipDirectoryWithOptions(testDir, destPath, options)

		if err != nil {
			t.Fatalf("压缩失败: %v", err)
		}

		if result.FileCount != 2 {
			t.Errorf("期望文件数 2, 实际 %d", result.FileCount)
		}
	})
}

// TestGetEncryptionMethod 测试加密类型转换
func TestGetEncryptionMethod(t *testing.T) {
	tests := []struct {
		name     string
		encType  ZipEncryptionType
		expected zip.EncryptionMethod
	}{
		{"StandardEncryption", ZipStandardEncryption, zip.StandardEncryption},
		{"AES128Encryption", ZipAES128Encryption, zip.AES128Encryption},
		{"AES192Encryption", ZipAES192Encryption, zip.AES192Encryption},
		{"AES256Encryption", ZipAES256Encryption, zip.AES256Encryption},
		{"Default", ZipEncryptionType(999), zip.AES256Encryption}, // 未知类型默认AES256
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			method := getEncryptionMethod(tt.encType)
			if method != tt.expected {
				t.Errorf("期望加密方法 %v, 实际 %v", tt.expected, method)
			}
		})
	}
}

// TestCalculateCompressionRatio 测试压缩率计算
func TestCalculateCompressionRatio(t *testing.T) {
	tests := []struct {
		name           string
		originalSize   int64
		compressedSize int64
		expected       float64
	}{
		{"NormalCase", 1000, 500, 50.0},
		{"NoCompression", 1000, 1000, 100.0},
		{"HighCompression", 1000, 100, 10.0},
		{"ZeroOriginal", 0, 100, 0.0},
		{"LargerCompressed", 100, 200, 200.0},
		{"BothZero", 0, 0, 0.0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ratio := calculateCompressionRatio(tt.originalSize, tt.compressedSize)
			if ratio != tt.expected {
				t.Errorf("期望压缩率 %.2f, 实际 %.2f", tt.expected, ratio)
			}
		})
	}
}

// TestGetCurrentTimestamp 测试时间戳获取
func TestGetCurrentTimestamp(t *testing.T) {
	timestamp := getCurrentTimestamp()

	if timestamp <= 0 {
		t.Error("时间戳应大于0")
	}

	// 验证时间戳是合理的（在最近的范围内）
	now := int64(1747843200) // 2025-05-21 00:00:00 UTC 近似值
	if timestamp < now-86400 || timestamp > now+86400 {
		t.Logf("警告: 时间戳可能不准确: %d", timestamp)
	}
}

// TestZipOptionsDefaults 测试选项默认值
func TestZipOptionsDefaults(t *testing.T) {
	tempDir := t.TempDir()
	testFiles := createTestFiles(t, tempDir, 1)

	// 测试空选项时使用默认值
	destPath := filepath.Join(tempDir, "test_defaults.zip")
	result, err := ZipFilesFromPathsWithOptions(testFiles, destPath, &ZipOptions{})

	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	if result == nil {
		t.Fatal("结果不应为nil")
	}

	if result.FileCount != 1 {
		t.Errorf("期望文件数 1, 实际 %d", result.FileCount)
	}
}

// TestZipWithSpecialFilenames 测试特殊文件名
func TestZipWithSpecialFilenames(t *testing.T) {
	tempDir := t.TempDir()

	// 创建带有特殊字符的文件名
	specialNames := []string{
		"file with spaces.txt",
		"file-with-dashes.txt",
		"file_with_underscores.txt",
		"文件中文名称.txt",
	}

	var files []string
	for _, name := range specialNames {
		content := fmt.Sprintf("Content of %s", name)
		filePath := createTestFile(t, tempDir, name, content)
		files = append(files, filePath)
	}

	destPath := filepath.Join(tempDir, "test_special_names.zip")
	result, err := ZipFilesFromPaths(files, destPath, "password123")

	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	if result.FileCount != len(specialNames) {
		t.Errorf("期望文件数 %d, 实际 %d", len(specialNames), result.FileCount)
	}
}

// TestZipLargeFile 测试大文件压缩
func TestZipLargeFile(t *testing.T) {
	if testing.Short() {
		t.Skip("跳过大型文件测试")
	}

	tempDir := t.TempDir()

	// 创建一个较大的测试文件 (1MB)
	largeContent := strings.Repeat("This is a large file content for testing compression. ", 20000)
	largeFile := createTestFile(t, tempDir, "large_file.txt", largeContent)

	destPath := filepath.Join(tempDir, "test_large_file.zip")
	result, err := ZipFilesFromPaths([]string{largeFile}, destPath, "password123")

	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	if result.FileCount != 1 {
		t.Errorf("期望文件数 1, 实际 %d", result.FileCount)
	}

	// 验证压缩效果（文本应该能被显著压缩）
	originalSize := int64(len(largeContent))
	compressionRatio := float64(result.Size) / float64(originalSize) * 100

	t.Logf("原始大小: %d bytes, 压缩大小: %d bytes, 压缩率: %.2f%%",
		originalSize, result.Size, compressionRatio)

	// 文本文件通常能压缩到原来的10%以下
	if compressionRatio > 20 {
		t.Logf("警告: 压缩率较高 (%.2f%%)，可能压缩效果不佳", compressionRatio)
	}
}

// TestZipEmptyPassword 测试空密码行为
func TestZipEmptyPassword(t *testing.T) {
	tempDir := t.TempDir()
	testFiles := createTestFiles(t, tempDir, 2)

	// 空字符串密码
	destPath := filepath.Join(tempDir, "test_empty_password.zip")
	result, err := ZipFilesFromPaths(testFiles, destPath, "")

	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	if result.IsEncrypted {
		t.Error("空密码不应该加密")
	}
}

// TestZipDirectoryDeepStructure 测试深层目录结构
func TestZipDirectoryDeepStructure(t *testing.T) {
	tempDir := t.TempDir()

	// 创建深层目录结构
	deepDir := filepath.Join(tempDir, "level1", "level2", "level3", "level4")
	if err := os.MkdirAll(deepDir, 0755); err != nil {
		t.Fatalf("创建深层目录失败: %v", err)
	}

	// 在不同层级创建文件
	createTestFile(t, filepath.Join(tempDir, "level1"), "file1.txt", "content1")
	createTestFile(t, filepath.Join(tempDir, "level1", "level2"), "file2.txt", "content2")
	createTestFile(t, deepDir, "file3.txt", "content3")

	destPath := filepath.Join(tempDir, "test_deep_structure.zip")
	result, err := ZipDirectory(tempDir, destPath, "password123")

	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	// 应该包含所有非目录文件
	if result.FileCount < 3 {
		t.Errorf("期望至少3个文件, 实际 %d", result.FileCount)
	}
}

// TestGenerateLocalZipFiles 在本地目录生成示例压缩文件
func TestGenerateLocalZipFiles(t *testing.T) {
	// 获取当前工作目录
	workDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("获取工作目录失败: %v", err)
	}

	// 创建 files 目录用于存放生成的压缩文件
	filesDir := filepath.Join(workDir, "files")
	if err := os.MkdirAll(filesDir, 0755); err != nil {
		t.Fatalf("创建 files 目录失败: %v", err)
	}

	t.Logf("📂 工作目录: %s", workDir)
	t.Logf("📂 输出目录: %s", filesDir)

	// 压缩 ZIP_USAGE.md 文档
	usageDocPath := filepath.Join(workDir, "ZIP_USAGE.md")
	if _, statErr := os.Stat(usageDocPath); statErr != nil {
		t.Skipf("ZIP_USAGE.md 不存在: %v", statErr)
	}

	destPath := filepath.Join(filesDir, "zip_usage_demo.zip")
	result, err := ZipFilesFromPaths([]string{usageDocPath}, destPath, "123456")
	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	t.Logf("✅ zip_usage_demo.zip 生成成功")
	t.Logf("   路径: %s", result.Path)
	t.Logf("   大小: %d bytes (%.2f KB)", result.Size, float64(result.Size)/1024)
	t.Logf("   加密: %v", result.IsEncrypted)
	t.Logf("   密码: 123456")
	t.Logf("   文件数: %d", result.FileCount)
}

// ==================== 辅助函数 ====================

// createTestFiles 创建多个测试文件
func createTestFiles(t *testing.T, dir string, count int) []string {
	t.Helper()
	var files []string
	for i := 1; i <= count; i++ {
		filename := fmt.Sprintf("test_file_%d.txt", i)
		content := fmt.Sprintf("This is test file content number %d", i)
		filePath := createTestFile(t, dir, filename, content)
		files = append(files, filePath)
	}
	return files
}

// createTestFile 创建单个测试文件
func createTestFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	filePath := filepath.Join(dir, name)
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		t.Fatalf("创建测试文件失败 [%s]: %v", name, err)
	}
	return filePath
}

// TestZipFilesIntegration 集成测试：压缩后验证文件完整性
func TestZipFilesIntegration(t *testing.T) {
	if testing.Short() {
		t.Skip("跳过集成测试")
	}

	tempDir := t.TempDir()

	// 创建测试文件
	file1 := createTestFile(t, tempDir, "integration_test_1.txt", "Integration test content 1")
	file2 := createTestFile(t, tempDir, "integration_test_2.txt", "Integration test content 2")

	// 压缩
	destPath := filepath.Join(tempDir, "integration_test.zip")
	result, err := ZipFilesFromPaths([]string{file1, file2}, destPath, "integration_password")

	if err != nil {
		t.Fatalf("压缩失败: %v", err)
	}

	// 验证压缩文件存在且大小合理
	fileInfo, err := os.Stat(destPath)
	if err != nil {
		t.Fatalf("压缩文件不存在: %v", err)
	}

	if fileInfo.Size() <= 0 {
		t.Error("压缩文件大小应为正数")
	}

	// 验证结果信息
	if result.FileCount != 2 {
		t.Errorf("期望文件数 2, 实际 %d", result.FileCount)
	}

	if !result.IsEncrypted {
		t.Error("应该已加密")
	}

	t.Logf("压缩成功: 路径=%s, 大小=%d bytes, 文件数=%d, 已加密=%v",
		result.Path, result.Size, result.FileCount, result.IsEncrypted)
}

// TestZipUsageMarkdown 测试压缩ZIP_USAGE.md文档（真实场景）
func TestZipUsageMarkdown(t *testing.T) {
	// 获取当前工作目录
	workDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("获取工作目录失败: %v", err)
	}

	// ZIP_USAGE.md 文件的相对路径
	usageDocPath := filepath.Join(workDir, "ZIP_USAGE.md")

	// 检查文件是否存在
	if _, statErr := os.Stat(usageDocPath); statErr != nil {
		t.Skipf("ZIP_USAGE.md 文件不存在: %v (可能不在 tools 目录下运行测试)", statErr)
	}

	// 在 files 目录生成压缩文件
	filesDir := filepath.Join(workDir, "files")
	if err := os.MkdirAll(filesDir, 0755); err != nil {
		t.Fatalf("创建 files 目录失败: %v", err)
	}
	destPath := filepath.Join(filesDir, "zip_usage_documentation.zip")

	// 使用密码 123456 压缩
	password := "123456"
	result, err := ZipFilesFromPaths([]string{usageDocPath}, destPath, password)

	if err != nil {
		t.Fatalf("压缩 ZIP_USAGE.md 失败: %v", err)
	}

	// 验证压缩结果
	if result == nil {
		t.Fatal("压缩结果不应为nil")
	}

	if result.Path != destPath {
		t.Errorf("期望路径 %s, 实际 %s", destPath, result.Path)
	}

	if result.FileCount != 1 {
		t.Errorf("期望文件数 1, 实际 %d", result.FileCount)
	}

	if !result.IsEncrypted {
		t.Error("应该已加密（密码: 123456）")
	}

	if result.Size <= 0 {
		t.Error("压缩文件大小应大于0")
	}

	// 验证压缩文件确实存在
	fileInfo, statErr := os.Stat(destPath)
	if statErr != nil {
		t.Fatalf("压缩文件不存在: %v", statErr)
	}

	// 读取原始文件大小进行对比
	originalFileInfo, _ := os.Stat(usageDocPath)
	originalSize := originalFileInfo.Size()
	compressedSize := fileInfo.Size()

	compressionRatio := float64(compressedSize) / float64(originalSize) * 100

	t.Logf("✅ ZIP_USAGE.md 压缩成功!")
	t.Logf("   原始文件: %s", usageDocPath)
	t.Logf("   原始大小: %d bytes (%.2f KB)", originalSize, float64(originalSize)/1024)
	t.Logf("   压缩文件: %s", destPath)
	t.Logf("   压缩大小: %d bytes (%.2f KB)", compressedSize, float64(compressedSize)/1024)
	t.Logf("   压缩率: %.2f%%", compressionRatio)
	t.Logf("   密码: %s", password)
	t.Logf("   加密类型: AES-256")
	t.Logf("   文件数量: %d", result.FileCount)
}
