package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/18721889353/sunshine/pkg/gofile"
	"github.com/18721889353/sunshine/pkg/jy2struct"
)

// Test_convertToGoFile_GenerateToTestdata 完整端到端测试：执行 YAML 转 Go 结构体并复制到 testdata 供查看
func Test_convertToGoFile_GenerateToTestdata(t *testing.T) {
	// 先生成到临时目录，再复制到 testdata 供查看
	tmpOut := filepath.Join(os.TempDir(), "sunshine-test", "config-gen")
	if err := os.RemoveAll(tmpOut); err != nil {
		t.Fatalf("清理旧输出目录失败: %v", err)
	}

	// 目标目录：测试文件同级目录下的 testdata
	testDataDir := filepath.Join("testdata", "config-gen")
	if err := os.RemoveAll(testDataDir); err != nil {
		t.Fatalf("清理旧 testdata 目录失败: %v", err)
	}

	// 真实案例：一个三层结构的 YAML 配置文件
	yamlContent := `
server:
  host: 0.0.0.0
  port: 8080
  timeout: 30
database:
  driver: mysql
  dsn: root:123456@tcp(192.168.1.1:3306)/test_db
  maxOpenConns: 100
  maxIdleConns: 10
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
`

	outDir := filepath.Join(tmpOut, "output")

	args := jy2struct.Args{
		Format:    "yaml",
		Data:      yamlContent,
		InputFile: "app-config.yml",
		SubStruct: true,
		Tags:      "json",
	}

	err := convertToGoFile(args, outDir)
	if err != nil {
		t.Fatalf("convertToGoFile() 失败: %v", err)
	}

	// 找到生成的 .go 文件
	generatedFile := filepath.Join(outDir, "internal", "config", "app-config.go")
	if !gofile.IsExists(generatedFile) {
		t.Fatalf("生成的 .go 文件不存在: %s", generatedFile)
	}
	t.Logf("生成的文件: %s", generatedFile)

	// 复制到 testdata 目录供查看
	relPath := "app-config.go"
	targetFile := filepath.Join(testDataDir, "internal", "config", relPath)
	if err := os.MkdirAll(filepath.Dir(targetFile), 0755); err != nil {
		t.Fatalf("创建目标目录失败: %v", err)
	}
	copyFile(t, generatedFile, targetFile)
	t.Logf("已复制到: %s", targetFile)

	// 验证文件内容
	data, err := os.ReadFile(generatedFile)
	if err != nil {
		t.Fatalf("读取生成文件失败: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "code generated by") {
		t.Error("生成文件缺少代码生成头")
	}
	if !strings.Contains(content, "package config") {
		t.Error("生成文件缺少 package config")
	}
	// 验证结构体
	if !strings.Contains(content, "Server") {
		t.Error("生成文件应包含 Server 结构体")
	}
	if !strings.Contains(content, "Database") {
		t.Error("生成文件应包含 Database 结构体")
	}
	if !strings.Contains(content, "Redis") {
		t.Error("生成文件应包含 Redis 结构体")
	}
	// 验证字段值
	if !strings.Contains(content, "MaxOpenConns") {
		t.Error("生成文件应包含 MaxOpenConns 字段")
	}
	if !strings.Contains(content, "MaxIdleConns") {
		t.Error("生成文件应包含 MaxIdleConns 字段")
	}
}
