package generate

const (
	dockerFileHTTPCode = `# 安装 curl，用于 http 服务健康检查；若部署在 k8s 可不安装
RUN apk add curl

COPY --chown=appuser:appuser configs/ /app/configs/
COPY --chown=appuser:appuser serverNameExample /app/serverNameExample
RUN chmod +x /app/serverNameExample

# http 端口
EXPOSE 8080`

	dockerFileGrpcCode = `# k8s 探针已改用原生 grpc: 方式（见 deployment.yml），无需在镜像内安装 grpc_health_probe

COPY --chown=appuser:appuser configs/ /app/configs/
COPY --chown=appuser:appuser serverNameExample /app/serverNameExample
RUN chmod +x /app/serverNameExample
`

	dockerFileBuildHTTPCode = `# 安装 curl，用于 http 服务健康检查；若部署在 k8s 可不安装
RUN apk add curl

# 从构建阶段复制产物
COPY --from=builder --chown=appuser:appuser /serverNameExample /app/serverNameExample
COPY --from=builder --chown=appuser:appuser /app/configs/serverNameExample.yml /app/configs/serverNameExample.yml

# http 端口
EXPOSE 8080`

	dockerFileBuildGrpcCode = `# k8s 探针已改用原生 grpc: 方式（见 deployment.yml），无需在镜像内安装 grpc_health_probe

# 从构建阶段复制产物
COPY --from=builder --chown=appuser:appuser /serverNameExample /app/serverNameExample
COPY --from=builder --chown=appuser:appuser /app/configs/serverNameExample.yml /app/configs/serverNameExample.yml
`

	imageBuildFileHTTPCode = `# 压缩二进制文件
#cd ${DOCKERFILE_PATH}
#upx -9 ${serverName}
#cd -

echo "docker build -f ${DOCKERFILE} -t ${IMAGE_NAME_TAG} ${DOCKERFILE_PATH}"
docker build -f ${DOCKERFILE} -t ${IMAGE_NAME_TAG} ${DOCKERFILE_PATH}`

	imageBuildFileGrpcCode = `# k8s 探针已改用原生 grpc: 方式（见 deployment.yml），无需再编译安装 grpc_health_probe

# 压缩二进制文件
#cd ${DOCKERFILE_PATH}
#upx -9 ${serverName}
#cd -

echo "docker build -f ${DOCKERFILE} -t ${IMAGE_NAME_TAG} ${DOCKERFILE_PATH}"
docker build -f ${DOCKERFILE} -t ${IMAGE_NAME_TAG} ${DOCKERFILE_PATH}`

	imageBuildLocalFileHTTPCode = `# 压缩二进制文件
#cd ${DOCKERFILE_PATH}
#upx -9 ${serverName}
#cd -

mkdir -p ${DOCKERFILE_PATH}/configs && cp -f configs/${serverName}.yml configs/${serverName}_cc.yml ${DOCKERFILE_PATH}/configs/
echo "docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:latest ${DOCKERFILE_PATH}"
docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:latest ${DOCKERFILE_PATH}`

	imageBuildLocalFileGrpcCode = `# k8s 探针已改用原生 grpc: 方式（见 deployment.yml），无需再编译安装 grpc_health_probe

# 压缩二进制文件
#cd ${DOCKERFILE_PATH}
#upx -9 ${serverName}
#cd -

mkdir -p ${DOCKERFILE_PATH}/configs && cp -f configs/${serverName}.yml configs/${serverName}_cc.yml ${DOCKERFILE_PATH}/configs/
echo "docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:latest ${DOCKERFILE_PATH}"
docker build -f ${DOCKERFILE} -t ${IMAGE_NAME}:latest ${DOCKERFILE_PATH}`

	dockerComposeFileHTTPCode = `    ports:
      - "8080:8080"   # http 端口
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]   # http 健康检查，注意：镜像内必须包含 curl 命令`

	dockerComposeFileGrpcCode = `
    ports:
      - "8282:8282"   # grpc 端口
      - "8283:8283"   # grpc metrics 或 pprof 端口
    # k8s 探针已改用原生 grpc: 方式（见 deployment.yml），镜像内不再安装 grpc_health_probe；
    # docker-compose 无原生 grpc 探针，如需启用 grpc 健康检查（exec 方式），须先在镜像内自行安装 grpc_health_probe
    #healthcheck:
    #  test: ["CMD", "grpc_health_probe", "-addr=localhost:8282"]    # grpc 健康检查，注意：镜像内必须包含 grpc_health_probe 命令`

	k8sDeploymentFileHTTPCode = `
          ports:
            - name: http-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-port
              path: /health`

	k8sDeploymentFileGrpcCode = `
          ports:
            - name: grpc-port
              containerPort: 8282
            - name: metrics-port
              containerPort: 8283
          readinessProbe:
            grpc:                          # K8s 原生 gRPC 健康检查（需 K8s >= 1.24），kubelet 直连，无需容器内探针工具
              port: 8282                   # gRPC 服务端口
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            grpc:                          # K8s 原生 gRPC 健康检查（需 K8s >= 1.24）
              port: 8282                   # gRPC 服务端口`

	k8sServiceFileHTTPCode = `  ports:
    - name: server-name-example-svc-http-port
      port: 8080
      targetPort: 8080`

	k8sServiceFileGrpcCode = `  ports:
    - name: server-name-example-svc-grpc-port
      port: 8282
      targetPort: 8282
    - name: server-name-example-svc-grpc-metrics-port
      port: 8283
      targetPort: 8283`

	configFileCode = `// code generated by https://github.com/18721889353/sunshine

package config

import (
	"github.com/18721889353/sunshine/pkg/conf"
)

var config *Config

func Init(configFile string, fs ...func()) error {
	config = &Config{}
	return conf.Parse(configFile, config, fs...)
}

func Show(hiddenFields ...string) string {
	return conf.Show(config, hiddenFields...)
}

func Get() *Config {
	if config == nil {
		panic("config is nil, please call config.Init() first")
	}
	return config
}

func Set(conf *Config) {
	config = conf
}
`

	configFileCcCode = `// code generated by https://github.com/18721889353/sunshine

package config

import (
	"github.com/18721889353/sunshine/pkg/conf"
)

func NewCenter(configFile string) (*Center, error) {
	nacosConf := &Center{}
	err := conf.Parse(configFile, nacosConf)
	return nacosConf, err
}
`

	protoShellGRPCMark = `
  # generate files *_grpc_pb.go
  protoc --proto_path=. --proto_path=./third_party \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    $allProtoFiles

  checkResult $?`

	// for rpc and rpc-pb
	protoShellServiceTmplCode = `
  moduleName=$(cat docs/gen.info | head -1 | cut -d , -f 1)
  serverName=$(cat docs/gen.info | head -1 | cut -d , -f 2)
  suitedMonoRepo=$(cat docs/gen.info | head -1 | cut -d , -f 3)

  protoc --proto_path=. --proto_path=./third_party \
    --go-rpc-tmpl_out=. --go-rpc-tmpl_opt=paths=source_relative \
    --go-rpc-tmpl_opt=moduleName=${moduleName} --go-rpc-tmpl_opt=serverName=${serverName} --go-rpc-tmpl_opt=suitedMonoRepo=${suitedMonoRepo} \
    $specifiedProtoFiles

  checkResult $?

  sunshine merge rpc-pb
  checkResult $?

  tipMsg="${highBright}Tip:${markEnd} execute the command ${colorCyan}make run${markEnd} and then test grpc api in the file ${colorCyan}internal/service/xxx_client_test.go${markEnd}."
`

	// for http-pb
	protoShellHandlerCode = `
  # generate the swagger document and merge all files into docs/apis.swagger.json
  protoc --proto_path=. --proto_path=./third_party \
    --openapiv2_out=. --openapiv2_opt=logtostderr=true --openapiv2_opt=allow_merge=true --openapiv2_opt=merge_file_name=docs/apis.json \
    $specifiedProtoFiles

  checkResult $?

  sunshine web swagger --file=docs/apis.swagger.json
  checkResult $?

  moduleName=$(cat docs/gen.info | head -1 | cut -d , -f 1)
  serverName=$(cat docs/gen.info | head -1 | cut -d , -f 2)
  suitedMonoRepo=$(cat docs/gen.info | head -1 | cut -d , -f 3)

  protoc --proto_path=. --proto_path=./third_party \
    --go-gin_out=. --go-gin_opt=paths=source_relative --go-gin_opt=plugin=handler \
    --go-gin_opt=moduleName=${moduleName} --go-gin_opt=serverName=${serverName} --go-gin_opt=suitedMonoRepo=${suitedMonoRepo} \
    $specifiedProtoFiles

  checkResult $?

  sunshine merge http-pb
  checkResult $?

  tipMsg="${highBright}Tip:${markEnd} execute the command ${colorCyan}make run${markEnd} and then visit ${colorCyan}http://localhost:8080/apis/swagger/index.html${markEnd} in your browser. "
`

	// for rpc-gw
	protoShellServiceCode = `
  # Generate the swagger document and merge all files into docs/apis.swagger.json
  protoc --proto_path=. --proto_path=./third_party \
    --openapiv2_out=. --openapiv2_opt=logtostderr=true --openapiv2_opt=allow_merge=true --openapiv2_opt=merge_file_name=docs/apis.json \
    $specifiedProtoFiles

  checkResult $?

  sunshine micro swagger --file=docs/apis.swagger.json
  checkResult $?

  moduleName=$(cat docs/gen.info | head -1 | cut -d , -f 1)
  serverName=$(cat docs/gen.info | head -1 | cut -d , -f 2)
  suitedMonoRepo=$(cat docs/gen.info | head -1 | cut -d , -f 3)

  protoc --proto_path=. --proto_path=./third_party \
    --go-gin_out=. --go-gin_opt=paths=source_relative --go-gin_opt=plugin=service \
    --go-gin_opt=moduleName=${moduleName} --go-gin_opt=serverName=${serverName} --go-gin_opt=suitedMonoRepo=${suitedMonoRepo} \
    $specifiedProtoFiles

  checkResult $?

  sunshine merge rpc-gw-pb
  checkResult $?

  tipMsg="${highBright}Tip:${markEnd} execute the command ${colorCyan}make run${markEnd} and then visit ${colorCyan}http://localhost:8080/apis/swagger/index.html${markEnd} in your browser."
`

	//nolint for grpc-http
	protoShellServiceAndHandlerCode = `
  # generate the swagger document and merge all files into docs/apis.swagger.json
  protoc --proto_path=. --proto_path=./third_party \
    --openapiv2_out=. --openapiv2_opt=logtostderr=true --openapiv2_opt=allow_merge=true --openapiv2_opt=merge_file_name=docs/apis.json \
    $specifiedProtoFiles

  checkResult $?

  sunshine web swagger --file=docs/apis.swagger.json
  checkResult $?

  moduleName=$(cat docs/gen.info | head -1 | cut -d , -f 1)
  serverName=$(cat docs/gen.info | head -1 | cut -d , -f 2)
  suitedMonoRepo=$(cat docs/gen.info | head -1 | cut -d , -f 3)

  protoc --proto_path=. --proto_path=./third_party \
    --go-rpc-tmpl_out=. --go-rpc-tmpl_opt=paths=source_relative \
    --go-rpc-tmpl_opt=moduleName=${moduleName} --go-rpc-tmpl_opt=serverName=${serverName} --go-rpc-tmpl_opt=suitedMonoRepo=${suitedMonoRepo} \
    $specifiedProtoFiles

  checkResult $?

  sunshine merge rpc-pb
  checkResult $?

  protoc --proto_path=. --proto_path=./third_party \
    --go-gin_out=. --go-gin_opt=paths=source_relative --go-gin_opt=plugin=mix \
    --go-gin_opt=moduleName=${moduleName} --go-gin_opt=serverName=${serverName} --go-gin_opt=suitedMonoRepo=${suitedMonoRepo} \
    $specifiedProtoFiles

  checkResult $?

  sunshine merge http-pb
  checkResult $?

  tipMsg="${highBright}Tip:${markEnd} execute the command ${colorCyan}make run${markEnd} and then\n      1. test http api in your browser ${colorCyan}http://localhost:8080/apis/swagger/index.html${markEnd}\n      2. test grpc api in the file ${colorCyan}internal/service/xxx_client_test.go${markEnd}"
`

	httpServerConfigCode = `# http server settings
http:
  port: 8080                # listen port
  timeout: 0                # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, if enableHTTPProfile is true, it needs to set 0 or greater than 60s`

	rpcServerConfigCode = `# grpc server settings
grpc:
  port: 8282                # listen port
  httpPort: 8283            # profile and metrics ports
  enableToken: false        # whether to enable server-side token authentication, default appID=grpc, appKey=123456
  # serverSecure parameter setting
  # if type="", it means no secure connection, no need to fill in any parameters
  # if type="one-way", it means server-side certification, only the fields 'certFile' and 'keyFile' should be filled in
  # if type="two-way", it means both client and server side certification, fill in all fields
  serverSecure:
    type: ""                # secures type, "", "one-way", "two-way"
    caFile: ""              # ca certificate file, valid only in "two-way", absolute path
    certFile: ""            # server side cert file, absolute path
    keyFile: ""             # server side key file, absolute path


# grpc client-side settings, support for setting up multiple grpc clients.
grpcClient:
  - name: "your_grpc_service_name"    # grpc service name, used for service discovery
    host: "127.0.0.1"            # grpc service address, used for direct connection
    port: 8282                   # grpc service port
    timeout: 0                   # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, valid only for unary grpc type
    registryDiscoveryType: ""    # registration and discovery types: consul, etcd, nacos, if empty, connecting to server using host and port
    # clientSecure parameter setting
    # if type="", it means no secure connection, no need to fill in any parameters
    # if type="one-way", it means server-side certification, only the fields 'serverName' and 'certFile' should be filled in
    # if type="two-way", it means both client and server side certification, fill in all fields
    clientSecure:
      type: ""              # secures type, "", "one-way", "two-way"
      serverName: ""        # server name, e.g. *.foo.com
      caFile: ""            # client side ca file, valid only in "two-way", absolute path
      certFile: ""          # client side cert file, absolute path, if secureType="one-way", fill in server side cert file here
      keyFile: ""           # client side key file, valid only in "two-way", absolute path
    clientToken:
      enable: false         # whether to enable token authentication
      appID: ""             # app id
      appKey: ""            # app key`

	rpcGwServerConfigCode = `# http server settings
http:
  port: 8080                # listen port
  timeout: 0                 # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, if enableHTTPProfile is true, it needs to set 0 or greater than 60s


# grpc client-side settings, support for setting up multiple grpc clients.
grpcClient:
  - name: "your_grpc_service_name"    # grpc service name, used for service discovery
    host: "127.0.0.1"            # grpc service address, used for direct connection
    port: 8282                   # grpc service port
    timeout: 0                   # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, valid only for unary grpc type
    registryDiscoveryType: ""    # registration and discovery types: consul, etcd, nacos, if empty, connecting to server using host and port
    # clientSecure parameter setting
    # if type="", it means no secure connection, no need to fill in any parameters
    # if type="one-way", it means server-side certification, only the fields 'serverName' and 'certFile' should be filled in
    # if type="two-way", it means both client and server side certification, fill in all fields
    clientSecure:
      type: ""              # secures type, "", "one-way", "two-way"
      serverName: ""        # server name, e.g. *.foo.com
      caFile: ""            # client side ca file, valid only in "two-way", absolute path
      certFile: ""          # client side cert file, absolute path, if secureType="one-way", fill in server side cert file here
      keyFile: ""           # client side key file, valid only in "two-way", absolute path
    clientToken:
      enable: false         # whether to enable token authentication
      appID: ""             # app id
      appKey: ""            # app key`

	grpcAndHTTPServerConfigCode = `# http server settings
http:
  port: 8080                # listen port
  timeout: 0                # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, if enableHTTPProfile is true, it needs to set 0 or greater than 60s


# grpc server settings
grpc:
  port: 8282                # listen port
  httpPort: 8283            # profile and metrics ports
  enableToken: false        # whether to enable server-side token authentication, default appID=grpc, appKey=123456
  # serverSecure parameter setting
  # if type="", it means no secure connection, no need to fill in any parameters
  # if type="one-way", it means server-side certification, only the fields 'certFile' and 'keyFile' should be filled in
  # if type="two-way", it means both client and server side certification, fill in all fields
  serverSecure:
    type: ""                # secures type, "", "one-way", "two-way"
    caFile: ""              # ca certificate file, valid only in "two-way", absolute path
    certFile: ""            # server side cert file, absolute path
    keyFile: ""             # server side key file, absolute path


# grpc client-side settings, support for setting up multiple grpc clients.
grpcClient:
  - name: "your_grpc_service_name"    # grpc service name, used for service discovery
    host: "127.0.0.1"            # grpc service address, used for direct connection
    port: 8282                   # grpc service port
    timeout: 0                   # request timeout, unit(second), if 0 means not set, if greater than 0 means set timeout, valid only for unary grpc type
    registryDiscoveryType: ""    # registration and discovery types: consul, etcd, nacos, if empty, connecting to server using host and port
    # clientSecure parameter setting
    # if type="", it means no secure connection, no need to fill in any parameters
    # if type="one-way", it means server-side certification, only the fields 'serverName' and 'certFile' should be filled in
    # if type="two-way", it means both client and server side certification, fill in all fields
    clientSecure:
      type: ""              # secures type, "", "one-way", "two-way"
      serverName: ""        # server name, e.g. *.foo.com
      caFile: ""            # client side ca file, valid only in "two-way", absolute path
      certFile: ""          # client side cert file, absolute path, if secureType="one-way", fill in server side cert file here
      keyFile: ""           # client side key file, valid only in "two-way", absolute path
    clientToken:
      enable: false         # whether to enable token authentication
      appID: ""             # app id
      appKey: ""            # app key`

	mysqlConfigCode = `# database setting
database:
  driver: "mysql"           # database driver
  # mysql settings
  mysql:
    # dsn format,  <username>:<password>@(<hostname>:<port>)/<db>?[k=v& ......]
    dsn: "root:123456@(192.168.3.37:3306)/account?parseTime=true&loc=Local&charset=utf8,utf8mb4"
    enableLog: true         # whether to turn on printing of all logs
    maxIdleConns: 10        # 设置空闲连接池中最大连接数
    maxOpenConns: 100       # 设置数据库最大打开连接数
    connMaxLifetime: 30     # 设置连接可重用的最大时间
    maxIdleTime: 10         # 设置空闲连接的最大空闲时间
    #slavesDsn:             # sets slaves mysql dsn, array type
    #  - "your slave dsn 1"
    #  - "your slave dsn 2"
    #mastersDsn:            # sets masters mysql dsn, array type, non-required field, if there is only one master, there is no need to set the mastersDsn field, the default dsn field is mysql master.
    #  - "your master dsn`

	undeterminedDatabaseConfigCode = `# database setting
database:
  driver: "mysql"           # database driver
  # mysql settings
  mysql:
    # dsn format,  <username>:<password>@(<hostname>:<port>)/<db>?[k=v& ......]
    dsn: "root:123456@(192.168.3.37:3306)/account?parseTime=true&loc=Local&charset=utf8,utf8mb4"
    enableLog: true         # whether to turn on printing of all logs
    maxIdleConns: 10        # 设置空闲连接池中最大连接数
    maxOpenConns: 100       # 设置数据库最大打开连接数
    connMaxLifetime: 30     # 设置连接可重用的最大时间
    maxIdleTime: 10         # 设置空闲连接的最大空闲时间
    #slavesDsn:             # sets slaves mysql dsn, array type
    #  - "your slave dsn 1"
    #  - "your slave dsn 2"
    #mastersDsn:            # sets masters mysql dsn, array type, non-required field, if there is only one master, there is no need to set the mastersDsn field, the default dsn field is mysql master.
    #  - "your master dsn`

	modelInitDBFileMysqlCode = `// InitDB connect database
func InitDB() {
	dbDriver := config.Get().Database.Driver
	switch strings.ToLower(dbDriver) {
	case sgorm.DBDriverMysql:
		gdb = InitMysql()
	default:
		panic("InitDB error, please modify the correct 'database' configuration at yaml file. " +
			"Refer to https://github.com/18721889353/sunshine/blob/main/configs/serverNameExample.yml#L85")
	}
}`

	embedTimeCode = `value.CreatedAt = record.CreatedAt.Format(time.RFC3339)
	value.UpdatedAt = record.UpdatedAt.Format(time.RFC3339)`
)
