// code generated by https://github.com/18721889353/sunshine

package config

import (
	"github.com/18721889353/sunshine/pkg/conf"
)

var config *Config

func Init(configFile string, fs ...func()) error {
	config = &Config{}
	return conf.Parse(configFile, config, fs...)
}

func Show(hiddenFields ...string) string {
	return conf.Show(config, hiddenFields...)
}

func Get() *Config {
	if config == nil {
		panic("config is nil, please call config.Init() first")
	}
	return config
}

func Set(conf *Config) {
	config = conf
}

type Config struct {
	App           App           `yaml:"app" json:"app"`
	Database      Database      `yaml:"database" json:"database"`
	Elasticsearch Elasticsearch `yaml:"elasticsearch" json:"elasticsearch"`
	Email         Email         `yaml:"email" json:"email"`
	Etcd          Etcd          `yaml:"etcd" json:"etcd"`
	Grpc          Grpc          `yaml:"grpc" json:"grpc"`
	GrpcClient    []GrpcClient  `yaml:"grpcClient" json:"grpcClient"`
	HTTP          HTTP          `yaml:"http" json:"http"`
	Jaeger        Jaeger        `yaml:"jaeger" json:"jaeger"`
	Jwt           Jwt           `yaml:"jwt" json:"jwt"`
	Logger        Logger        `yaml:"logger" json:"logger"`
	Rabbitmq      Rabbitmq      `yaml:"rabbitmq" json:"rabbitmq"`
	Redis         Redis         `yaml:"redis" json:"redis"`
	Sentinel      Sentinel      `yaml:"sentinel" json:"sentinel"`
	Sign          Sign          `yaml:"sign" json:"sign"`
	Sls           Sls           `yaml:"sls" json:"sls"`
}

type Email struct {
	AccessKeyID  string `yaml:"accessKeyID" json:"accessKeyID"`
	ProviderType string `yaml:"providerType" json:"providerType"`
	Region       string `yaml:"region" json:"region"`
	SecretKey    string `yaml:"secretKey" json:"secretKey"`
	SMTP         SMTP   `yaml:"smtp" json:"smtp"`
}

type Sls struct {
	AccessKeyID           string `yaml:"accessKeyId" json:"accessKeyId"`
	AccessKeySecret       string `yaml:"accessKeySecret" json:"accessKeySecret"`
	DisableRuntimeMetrics bool   `yaml:"disableRuntimeMetrics" json:"disableRuntimeMetrics"`
	Enable                bool   `yaml:"enable" json:"enable"`
	EnableHealthCheck     bool   `yaml:"enableHealthCheck" json:"enableHealthCheck"`
	Endpoint              string `yaml:"endpoint" json:"endpoint"`
	HealthCheckInterval   int    `yaml:"healthCheckInterval" json:"healthCheckInterval"`
	LingerMs              int    `yaml:"lingerMs" json:"lingerMs"`
	Logstore              string `yaml:"logstore" json:"logstore"`
	MaxBatchCount         int    `yaml:"maxBatchCount" json:"maxBatchCount"`
	MaxBatchSize          int    `yaml:"maxBatchSize" json:"maxBatchSize"`
	Project               string `yaml:"project" json:"project"`
	Retries               int    `yaml:"retries" json:"retries"`
	SendTimeout           int    `yaml:"sendTimeout" json:"sendTimeout"`
	Source                string `yaml:"source" json:"source"`
	Timeout               int    `yaml:"timeout" json:"timeout"`
	Topic                 string `yaml:"topic" json:"topic"`
	TotalSizeLnBytes      int    `yaml:"totalSizeLnBytes" json:"totalSizeLnBytes"`
}

type Elasticsearch struct {
	Addresses             []string `yaml:"addresses" json:"addresses"`
	APIKey                string   `yaml:"apiKey" json:"apiKey"`
	ConnectionKeepAlive   int      `yaml:"connectionKeepAlive" json:"connectionKeepAlive"`
	ConnectionTimeout     int      `yaml:"connectionTimeout" json:"connectionTimeout"`
	EnableHealthCheck     bool     `yaml:"enableHealthCheck" json:"enableHealthCheck"`
	EnablePingCheck       bool     `yaml:"enablePingCheck" json:"enablePingCheck"`
	ExpectContinueTimeout int      `yaml:"expectContinueTimeout" json:"expectContinueTimeout"`
	IdleConnTimeout       int      `yaml:"idleConnTimeout" json:"idleConnTimeout"`
	IsOpen                bool     `yaml:"isOpen" json:"isOpen"`
	MaxConnsPerHost       int      `yaml:"maxConnsPerHost" json:"maxConnsPerHost"`
	MaxIdleConns          int      `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxIdleConnsPerHost   int      `yaml:"maxIdleConnsPerHost" json:"maxIdleConnsPerHost"`
	MaxRetries            int      `yaml:"maxRetries" json:"maxRetries"`
	Password              string   `yaml:"password" json:"password"`
	ResponseHeaderTimeout int      `yaml:"responseHeaderTimeout" json:"responseHeaderTimeout"`
	RetryBackoff          int      `yaml:"retryBackoff" json:"retryBackoff"`
	RetryOnStatus         []int    `yaml:"retryOnStatus" json:"retryOnStatus"`
	Timeout               int      `yaml:"timeout" json:"timeout"`
	TLSHandshakeTimeout   int      `yaml:"tlsHandshakeTimeout" json:"tlsHandshakeTimeout"`
	Username              string   `yaml:"username" json:"username"`
}

type Etcd struct {
	Addrs []string `yaml:"addrs" json:"addrs"`
}

type Jaeger struct {
	AgentHost string `yaml:"agentHost" json:"agentHost"`
	AgentPort int    `yaml:"agentPort" json:"agentPort"`
	Endpoint  string `yaml:"endpoint" json:"endpoint"`
}

type Pool struct {
	AntsCap           int    `yaml:"antsCap" json:"antsCap"`
	DialTimeout       int    `yaml:"dialTimeout" json:"dialTimeout"`
	HealthCheckPeriod int    `yaml:"healthCheckPeriod" json:"healthCheckPeriod"`
	Heartbeat         int    `yaml:"heartbeat" json:"heartbeat"`
	InitialCap        int    `yaml:"initialCap" json:"initialCap"`
	MaxCap            int    `yaml:"maxCap" json:"maxCap"`
	MaxIdle           int    `yaml:"maxIdle" json:"maxIdle"`
	ReconnectTime     int    `yaml:"reconnectTime" json:"reconnectTime"`
	StatsLogOpen      bool   `yaml:"statsLogOpen" json:"statsLogOpen"`
	URL               string `yaml:"url" json:"url"`
}

type ClientToken struct {
	AppID  string `yaml:"appID" json:"appID"`
	AppKey string `yaml:"appKey" json:"appKey"`
	Enable bool   `yaml:"enable" json:"enable"`
}

type DeadQueueDeclareOption struct {
	Args       Args `yaml:"args" json:"args"`
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Exclusive  bool `yaml:"exclusive" json:"exclusive"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type Logger struct {
	AsyncBufferSize    int           `yaml:"asyncBufferSize" json:"asyncBufferSize"`
	AsyncFlushInterval int           `yaml:"asyncFlushInterval" json:"asyncFlushInterval"`
	Format             string        `yaml:"format" json:"format"`
	IsAsync            bool          `yaml:"isAsync" json:"isAsync"`
	IsSave             bool          `yaml:"isSave" json:"isSave"`
	Level              string        `yaml:"level" json:"level"`
	LogFileConfig      LogFileConfig `yaml:"logFileConfig" json:"logFileConfig"`
	MaxLen             int           `yaml:"maxLen" json:"maxLen"`
	Routes             []Routes      `yaml:"routes" json:"routes"`
}

type NormalQueueDeclareOption struct {
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Exclusive  bool `yaml:"exclusive" json:"exclusive"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type ExchangeDeclareOptions struct {
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Internal   bool `yaml:"internal" json:"internal"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type ClientSecure struct {
	CaFile     string `yaml:"caFile" json:"caFile"`
	CertFile   string `yaml:"certFile" json:"certFile"`
	KeyFile    string `yaml:"keyFile" json:"keyFile"`
	ServerName string `yaml:"serverName" json:"serverName"`
	Type       string `yaml:"type" json:"type"`
}

type ServerSecure struct {
	CaFile   string `yaml:"caFile" json:"caFile"`
	CertFile string `yaml:"certFile" json:"certFile"`
	KeyFile  string `yaml:"keyFile" json:"keyFile"`
	Type     string `yaml:"type" json:"type"`
}

type App struct {
	CacheType             string  `yaml:"cacheType" json:"cacheType"`
	EnableCircuitBreaker  bool    `yaml:"enableCircuitBreaker" json:"enableCircuitBreaker"`
	EnableHTTPProfile     bool    `yaml:"enableHTTPProfile" json:"enableHTTPProfile"`
	EnableLimit           bool    `yaml:"enableLimit" json:"enableLimit"`
	EnableMetrics         bool    `yaml:"enableMetrics" json:"enableMetrics"`
	EnableStat            bool    `yaml:"enableStat" json:"enableStat"`
	EnableTrace           bool    `yaml:"enableTrace" json:"enableTrace"`
	Env                   string  `yaml:"env" json:"env"`
	Host                  string  `yaml:"host" json:"host"`
	MachineID             int     `yaml:"machineId" json:"machineId"`
	Name                  string  `yaml:"name" json:"name"`
	OpenCron              bool    `yaml:"openCron" json:"openCron"`
	OpenHTTP              bool    `yaml:"openHttp" json:"openHttp"`
	OpenJwt               bool    `yaml:"openJwt" json:"openJwt"`
	OpenSign              bool    `yaml:"openSign" json:"openSign"`
	OpenXSS               bool    `yaml:"openXSS" json:"openXSS"`
	RegistryDiscoveryType string  `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	TracingSamplingRate   float64 `yaml:"tracingSamplingRate" json:"tracingSamplingRate"`
	Version               string  `yaml:"version" json:"version"`
}

type GrpcClient struct {
	ClientSecure          ClientSecure `yaml:"clientSecure" json:"clientSecure"`
	ClientToken           ClientToken  `yaml:"clientToken" json:"clientToken"`
	EnableLoadBalance     bool         `yaml:"enableLoadBalance" json:"enableLoadBalance"`
	Host                  string       `yaml:"host" json:"host"`
	Name                  string       `yaml:"name" json:"name"`
	Port                  int          `yaml:"port" json:"port"`
	RegistryDiscoveryType string       `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	Timeout               int          `yaml:"timeout" json:"timeout"`
}

type Mysql struct {
	ConnMaxLifetime      int      `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	Dsn                  string   `yaml:"dsn" json:"dsn"`
	EnableLog            bool     `yaml:"enableLog" json:"enableLog"`
	MastersDsn           []string `yaml:"mastersDsn" json:"mastersDsn"`
	MaxIdleConns         int      `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxIdleTime          int      `yaml:"maxIdleTime" json:"maxIdleTime"`
	MaxOpenConns         int      `yaml:"maxOpenConns" json:"maxOpenConns"`
	SlavesDsn            []string `yaml:"slavesDsn" json:"slavesDsn"`
	SlowQueryThresholdMs int      `yaml:"slowQueryThresholdMs" json:"slowQueryThresholdMs"`
}

type ConsumerOption struct {
	Consumer      string `yaml:"consumer" json:"consumer"`
	Exclusive     bool   `yaml:"exclusive" json:"exclusive"`
	Global        bool   `yaml:"global" json:"global"`
	IsAutoAck     bool   `yaml:"isAutoAck" json:"isAutoAck"`
	MsgDurable    bool   `yaml:"msgDurable" json:"msgDurable"`
	NoLocal       bool   `yaml:"noLocal" json:"noLocal"`
	NoWait        bool   `yaml:"noWait" json:"noWait"`
	PrefetchCount int    `yaml:"prefetchCount" json:"prefetchCount"`
	PrefetchSize  int    `yaml:"prefetchSize" json:"prefetchSize"`
}

type DoingOrder struct {
	ConsumerNum              int                      `yaml:"consumerNum" json:"consumerNum"`
	ConsumerOption           ConsumerOption           `yaml:"consumerOption" json:"consumerOption"`
	DeadKey                  string                   `yaml:"deadKey" json:"deadKey"`
	DeadQueueBindOption      DeadQueueBindOption      `yaml:"deadQueueBindOption" json:"deadQueueBindOption"`
	DeadQueueDeclareOption   DeadQueueDeclareOption   `yaml:"deadQueueDeclareOption" json:"deadQueueDeclareOption"`
	DeadQueueName            string                   `yaml:"deadQueueName" json:"deadQueueName"`
	Enable                   bool                     `yaml:"enable" json:"enable"`
	ExchangeDeclareOptions   ExchangeDeclareOptions   `yaml:"exchangeDeclareOptions" json:"exchangeDeclareOptions"`
	ExchangeName             string                   `yaml:"exchangeName" json:"exchangeName"`
	NormalKey                string                   `yaml:"normalKey" json:"normalKey"`
	NormalQueueBindOption    DeadQueueBindOption      `yaml:"normalQueueBindOption" json:"normalQueueBindOption"`
	NormalQueueDeclareOption NormalQueueDeclareOption `yaml:"normalQueueDeclareOption" json:"normalQueueDeclareOption"`
	NormalQueueName          string                   `yaml:"normalQueueName" json:"normalQueueName"`
	QueueType                string                   `yaml:"queueType" json:"queueType"`
}

type Redis struct {
	DialTimeout  int    `yaml:"dialTimeout" json:"dialTimeout"`
	Dsn          string `yaml:"dsn" json:"dsn"`
	IdleTimeout  int    `yaml:"idleTimeout" json:"idleTimeout"`
	MaxConnAge   int    `yaml:"maxConnAge" json:"maxConnAge"`
	MinIdleConns int    `yaml:"minIdleConns" json:"minIdleConns"`
	PoolSize     int    `yaml:"poolSize" json:"poolSize"`
	PoolTimeout  int    `yaml:"poolTimeout" json:"poolTimeout"`
	ReadTimeout  int    `yaml:"readTimeout" json:"readTimeout"`
	WriteTimeout int    `yaml:"writeTimeout" json:"writeTimeout"`
}

type Rabbitmq struct {
	DoingOrder DoingOrder `yaml:"DoingOrder" json:"DoingOrder"`
	Enable     bool       `yaml:"enable" json:"enable"`
	Pool       Pool       `yaml:"pool" json:"pool"`
}

type Database struct {
	Driver string `yaml:"driver" json:"driver"`
	Mysql  Mysql  `yaml:"mysql" json:"mysql"`
}

type Grpc struct {
	EnableToken  bool         `yaml:"enableToken" json:"enableToken"`
	HTTPPort     int          `yaml:"httpPort" json:"httpPort"`
	Port         int          `yaml:"port" json:"port"`
	ServerSecure ServerSecure `yaml:"serverSecure" json:"serverSecure"`
}

type Jwt struct {
	Expire        int           `yaml:"expire" json:"expire"`
	IgnoreMethods IgnoreMethods `yaml:"ignoreMethods" json:"ignoreMethods"`
	Issuer        string        `yaml:"issuer" json:"issuer"`
	SigningKey    string        `yaml:"signingKey" json:"signingKey"`
	SigningMethod string        `yaml:"signingMethod" json:"signingMethod"`
}

type Routes struct {
	Filename      string `yaml:"filename" json:"filename"`
	Format        string `yaml:"format" json:"format"`
	IsAsync       bool   `yaml:"isAsync" json:"isAsync"`
	IsCompression bool   `yaml:"isCompression" json:"isCompression"`
	IsSaveDay     bool   `yaml:"isSaveDay" json:"isSaveDay"`
	MaxAge        int    `yaml:"maxAge" json:"maxAge"`
	MaxBackups    int    `yaml:"maxBackups" json:"maxBackups"`
	MaxSize       int    `yaml:"maxSize" json:"maxSize"`
	Module        string `yaml:"module" json:"module"`
}

type LogFileConfig struct {
	Filename      string `yaml:"filename" json:"filename"`
	IsCompression bool   `yaml:"isCompression" json:"isCompression"`
	IsNoPrint     bool   `yaml:"isNoPrint" json:"isNoPrint"`
	IsSaveDay     bool   `yaml:"isSaveDay" json:"isSaveDay"`
	MaxAge        int    `yaml:"maxAge" json:"maxAge"`
	MaxBackups    int    `yaml:"maxBackups" json:"maxBackups"`
	MaxSize       int    `yaml:"maxSize" json:"maxSize"`
}

type IgnoreMethods struct {
	Grpc []string `yaml:"grpc" json:"grpc"`
	HTTP []string `yaml:"http" json:"http"`
}

type SMTP struct {
	Host     string `yaml:"host" json:"host"`
	Password string `yaml:"password" json:"password"`
	Port     int    `yaml:"port" json:"port"`
	Username string `yaml:"username" json:"username"`
}

type Sign struct {
	IgnoreUrls      IgnoreMethods `yaml:"ignoreUrls" json:"ignoreUrls"`
	SignExpiredTime int           `yaml:"signExpiredTime" json:"signExpiredTime"`
	SignKey         string        `yaml:"signKey" json:"signKey"`
}

type DeadQueueBindOption struct {
	NoWait bool `yaml:"noWait" json:"noWait"`
}

type HTTP struct {
	Port    int `yaml:"port" json:"port"`
	Timeout int `yaml:"timeout" json:"timeout"`
}

type Rules struct {
	Resource         string  `yaml:"resource" json:"resource"`
	StatIntervalInMs int     `yaml:"statIntervalInMs" json:"statIntervalInMs"`
	Threshold        float64 `yaml:"threshold" json:"threshold"`
}

type Sentinel struct {
	Rules []Rules `yaml:"rules" json:"rules"`
}

type Args struct {
	XMessageTTL int `yaml:"xMessageTtl" json:"xMessageTtl"`
}
