// code generated by https://github.com/18721889353/sunshine

package config

import (
	"github.com/18721889353/sunshine/pkg/conf"
)

var config *Config

func Init(configFile string, fs ...func()) error {
	config = &Config{}
	return conf.Parse(configFile, config, fs...)
}

func Show(hiddenFields ...string) string {
	return conf.Show(config, hiddenFields...)
}

func Get() *Config {
	if config == nil {
		panic("config is nil, please call config.Init() first")
	}
	return config
}

func Set(conf *Config) {
	config = conf
}

type Config struct {
	App           App           `yaml:"app" json:"app"`
	Database      Database      `yaml:"database" json:"database"`
	Elasticsearch Elasticsearch `yaml:"elasticsearch" json:"elasticsearch"`
	Email         Email         `yaml:"email" json:"email"`
	EtcdInfo      EtcdInfo      `yaml:"etcdInfo" json:"etcdInfo"`
	Grpc          Grpc          `yaml:"grpc" json:"grpc"`
	GrpcClient    []GrpcClient  `yaml:"grpcClient" json:"grpcClient"`
	HTTP          HTTP          `yaml:"http" json:"http"`
	Jaeger        Jaeger        `yaml:"jaeger" json:"jaeger"`
	Jwt           Jwt           `yaml:"jwt" json:"jwt"`
	Logger        Logger        `yaml:"logger" json:"logger"`
	NacosInfo     NacosInfo     `yaml:"nacosInfo" json:"nacosInfo"`
	Rabbitmq      Rabbitmq      `yaml:"rabbitmq" json:"rabbitmq"`
	Redis         Redis         `yaml:"redis" json:"redis"`
	Sentinel      Sentinel      `yaml:"sentinel" json:"sentinel"`
	Sign          Sign          `yaml:"sign" json:"sign"`
	Sls           Sls           `yaml:"sls" json:"sls"`
	Sms           Sms           `yaml:"sms" json:"sms"`
	Websocket     Websocket     `yaml:"websocket" json:"websocket"`
}

type Sms struct {
	AccessKeyID  string `yaml:"accessKeyID" json:"accessKeyID"`
	AppID        string `yaml:"appID" json:"appID"`
	ProviderType string `yaml:"providerType" json:"providerType"`
	Region       string `yaml:"region" json:"region"`
	SecretKey    string `yaml:"secretKey" json:"secretKey"`
}

type Email struct {
	AccessKeyID  string `yaml:"accessKeyID" json:"accessKeyID"`
	ProviderType string `yaml:"providerType" json:"providerType"`
	Region       string `yaml:"region" json:"region"`
	SecretKey    string `yaml:"secretKey" json:"secretKey"`
	SMTP         SMTP   `yaml:"smtp" json:"smtp"`
}

type Sls struct {
	AccessKeyID           string `yaml:"accessKeyId" json:"accessKeyId"`
	AccessKeySecret       string `yaml:"accessKeySecret" json:"accessKeySecret"`
	DisableRuntimeMetrics bool   `yaml:"disableRuntimeMetrics" json:"disableRuntimeMetrics"`
	Enable                bool   `yaml:"enable" json:"enable"`
	EnableHealthCheck     bool   `yaml:"enableHealthCheck" json:"enableHealthCheck"`
	Endpoint              string `yaml:"endpoint" json:"endpoint"`
	HealthCheckInterval   int    `yaml:"healthCheckInterval" json:"healthCheckInterval"`
	LingerMs              int    `yaml:"lingerMs" json:"lingerMs"`
	Logstore              string `yaml:"logstore" json:"logstore"`
	MaxBatchCount         int    `yaml:"maxBatchCount" json:"maxBatchCount"`
	MaxBatchSize          int    `yaml:"maxBatchSize" json:"maxBatchSize"`
	Project               string `yaml:"project" json:"project"`
	Retries               int    `yaml:"retries" json:"retries"`
	SendTimeout           int    `yaml:"sendTimeout" json:"sendTimeout"`
	Source                string `yaml:"source" json:"source"`
	Timeout               int    `yaml:"timeout" json:"timeout"`
	Topic                 string `yaml:"topic" json:"topic"`
	TotalSizeLnBytes      int    `yaml:"totalSizeLnBytes" json:"totalSizeLnBytes"`
}

type Elasticsearch struct {
	Addresses             []string `yaml:"addresses" json:"addresses"`
	APIKey                string   `yaml:"apiKey" json:"apiKey"`
	ConnectionKeepAlive   int      `yaml:"connectionKeepAlive" json:"connectionKeepAlive"`
	ConnectionTimeout     int      `yaml:"connectionTimeout" json:"connectionTimeout"`
	EnableHealthCheck     bool     `yaml:"enableHealthCheck" json:"enableHealthCheck"`
	EnablePingCheck       bool     `yaml:"enablePingCheck" json:"enablePingCheck"`
	ExpectContinueTimeout int      `yaml:"expectContinueTimeout" json:"expectContinueTimeout"`
	IdleConnTimeout       int      `yaml:"idleConnTimeout" json:"idleConnTimeout"`
	IsOpen                bool     `yaml:"isOpen" json:"isOpen"`
	MaxConnsPerHost       int      `yaml:"maxConnsPerHost" json:"maxConnsPerHost"`
	MaxIdleConns          int      `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxIdleConnsPerHost   int      `yaml:"maxIdleConnsPerHost" json:"maxIdleConnsPerHost"`
	MaxRetries            int      `yaml:"maxRetries" json:"maxRetries"`
	Password              string   `yaml:"password" json:"password"`
	ResponseHeaderTimeout int      `yaml:"responseHeaderTimeout" json:"responseHeaderTimeout"`
	RetryBackoff          int      `yaml:"retryBackoff" json:"retryBackoff"`
	RetryOnStatus         []int    `yaml:"retryOnStatus" json:"retryOnStatus"`
	Timeout               int      `yaml:"timeout" json:"timeout"`
	TLSHandshakeTimeout   int      `yaml:"tlsHandshakeTimeout" json:"tlsHandshakeTimeout"`
	Username              string   `yaml:"username" json:"username"`
}

type EtcdServer struct {
	Addrs []string `yaml:"addrs" json:"addrs"`
}

type Jaeger struct {
	AgentHost string `yaml:"agentHost" json:"agentHost"`
	AgentPort int    `yaml:"agentPort" json:"agentPort"`
	Endpoint  string `yaml:"endpoint" json:"endpoint"`
}

type Upgrade struct {
	AllowedOrigins    []interface{} `yaml:"allowedOrigins" json:"allowedOrigins"`
	Cors              bool          `yaml:"cors" json:"cors"`
	EnableCompression bool          `yaml:"enableCompression" json:"enableCompression"`
	ReadBufferSize    int           `yaml:"readBufferSize" json:"readBufferSize"`
	Subprotocols      string        `yaml:"subprotocols" json:"subprotocols"`
	WriteBufferSize   int           `yaml:"writeBufferSize" json:"writeBufferSize"`
}

type ClientToken struct {
	AppID  string `yaml:"appID" json:"appID"`
	AppKey string `yaml:"appKey" json:"appKey"`
	Enable bool   `yaml:"enable" json:"enable"`
}

type DeadQueueDeclareOption struct {
	Args       Args `yaml:"args" json:"args"`
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Exclusive  bool `yaml:"exclusive" json:"exclusive"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type Logger struct {
	AsyncBufferSize    int           `yaml:"asyncBufferSize" json:"asyncBufferSize"`
	AsyncFlushInterval int           `yaml:"asyncFlushInterval" json:"asyncFlushInterval"`
	Format             string        `yaml:"format" json:"format"`
	IsAsync            bool          `yaml:"isAsync" json:"isAsync"`
	IsSave             bool          `yaml:"isSave" json:"isSave"`
	Level              string        `yaml:"level" json:"level"`
	LogFileConfig      LogFileConfig `yaml:"logFileConfig" json:"logFileConfig"`
	MaxLen             int           `yaml:"maxLen" json:"maxLen"`
	Routes             []Routes      `yaml:"routes" json:"routes"`
}

type ErrQueueDeclareOption struct {
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Exclusive  bool `yaml:"exclusive" json:"exclusive"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type ExchangeDeclareOptions struct {
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Internal   bool `yaml:"internal" json:"internal"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type EtcdClient struct {
	AutoSyncInterval     string `yaml:"autoSyncInterval" json:"autoSyncInterval"`
	CaFile               string `yaml:"caFile" json:"caFile"`
	CertFile             string `yaml:"certFile" json:"certFile"`
	DialKeepAliveTime    string `yaml:"dialKeepAliveTime" json:"dialKeepAliveTime"`
	DialKeepAliveTimeout string `yaml:"dialKeepAliveTimeout" json:"dialKeepAliveTimeout"`
	DialTimeout          string `yaml:"dialTimeout" json:"dialTimeout"`
	IsSecure             bool   `yaml:"isSecure" json:"isSecure"`
	Password             string `yaml:"password" json:"password"`
	ServerNameOverride   string `yaml:"serverNameOverride" json:"serverNameOverride"`
	Username             string `yaml:"username" json:"username"`
}

type EtcdRegistry struct {
	BackoffInit   string `yaml:"backoffInit" json:"backoffInit"`
	BackoffMax    string `yaml:"backoffMax" json:"backoffMax"`
	CheckInterval int    `yaml:"checkInterval" json:"checkInterval"`
	MaxRetry      int    `yaml:"maxRetry" json:"maxRetry"`
	Namespace     string `yaml:"namespace" json:"namespace"`
	TTL           string `yaml:"ttl" json:"ttl"`
}

type NacosRegistry struct {
	BackoffInit     string `yaml:"backoffInit" json:"backoffInit"`
	BackoffMax      string `yaml:"backoffMax" json:"backoffMax"`
	CheckInterval   string `yaml:"checkInterval" json:"checkInterval"`
	ClusterName     string `yaml:"clusterName" json:"clusterName"`
	Ephemeral       bool   `yaml:"ephemeral" json:"ephemeral"`
	GroupName       string `yaml:"groupName" json:"groupName"`
	Healthy         bool   `yaml:"healthy" json:"healthy"`
	RegisterEnabled bool   `yaml:"registerEnabled" json:"registerEnabled"`
	Weight          int    `yaml:"weight" json:"weight"`
}

type Sentinel struct {
	BreakerRules []BreakerRules `yaml:"breakerRules" json:"breakerRules"`
	LimitRules   []LimitRules   `yaml:"limitRules" json:"limitRules"`
}

type ClientSecure struct {
	CaFile     string `yaml:"caFile" json:"caFile"`
	CertFile   string `yaml:"certFile" json:"certFile"`
	KeyFile    string `yaml:"keyFile" json:"keyFile"`
	ServerName string `yaml:"serverName" json:"serverName"`
	Type       string `yaml:"type" json:"type"`
}

type ServerSecure struct {
	CaFile   string `yaml:"caFile" json:"caFile"`
	CertFile string `yaml:"certFile" json:"certFile"`
	KeyFile  string `yaml:"keyFile" json:"keyFile"`
	Type     string `yaml:"type" json:"type"`
}

type App struct {
	CacheType             string   `yaml:"cacheType" json:"cacheType"`
	EnableCircuitBreaker  bool     `yaml:"enableCircuitBreaker" json:"enableCircuitBreaker"`
	EnableHTTPProfile     bool     `yaml:"enableHTTPProfile" json:"enableHTTPProfile"`
	EnableLimit           bool     `yaml:"enableLimit" json:"enableLimit"`
	EnableMetrics         bool     `yaml:"enableMetrics" json:"enableMetrics"`
	EnableTrace           bool     `yaml:"enableTrace" json:"enableTrace"`
	Env                   string   `yaml:"env" json:"env"`
	Host                  string   `yaml:"host" json:"host"`
	Name                  string   `yaml:"name" json:"name"`
	OpenCron              bool     `yaml:"openCron" json:"openCron"`
	OpenHTTP              bool     `yaml:"openHttp" json:"openHttp"`
	OpenJwt               bool     `yaml:"openJwt" json:"openJwt"`
	OpenSign              bool     `yaml:"openSign" json:"openSign"`
	OpenXSS               bool     `yaml:"openXSS" json:"openXSS"`
	PprofIPWhiteList      []string `yaml:"pprofIPWhiteList" json:"pprofIPWhiteList"`
	RegistryDiscoveryType string   `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	TracingSamplingRate   float64  `yaml:"tracingSamplingRate" json:"tracingSamplingRate"`
	Version               string   `yaml:"version" json:"version"`
}

type GrpcClient struct {
	ClientSecure          ClientSecure `yaml:"clientSecure" json:"clientSecure"`
	ClientToken           ClientToken  `yaml:"clientToken" json:"clientToken"`
	EnableLoadBalance     bool         `yaml:"enableLoadBalance" json:"enableLoadBalance"`
	Host                  string       `yaml:"host" json:"host"`
	Name                  string       `yaml:"name" json:"name"`
	Port                  int          `yaml:"port" json:"port"`
	RegistryDiscoveryType string       `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	Timeout               int          `yaml:"timeout" json:"timeout"`
}

type Mysql struct {
	ConnMaxLifetime      int      `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	Dsn                  string   `yaml:"dsn" json:"dsn"`
	EnableLog            bool     `yaml:"enableLog" json:"enableLog"`
	MastersDsn           []string `yaml:"mastersDsn" json:"mastersDsn"`
	MaxIdleConns         int      `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxIdleTime          int      `yaml:"maxIdleTime" json:"maxIdleTime"`
	MaxOpenConns         int      `yaml:"maxOpenConns" json:"maxOpenConns"`
	SlavesDsn            []string `yaml:"slavesDsn" json:"slavesDsn"`
	SlowQueryThresholdMs int      `yaml:"slowQueryThresholdMs" json:"slowQueryThresholdMs"`
}

type ConsumerOption struct {
	Consumer      string `yaml:"consumer" json:"consumer"`
	Exclusive     bool   `yaml:"exclusive" json:"exclusive"`
	Global        bool   `yaml:"global" json:"global"`
	IsAutoAck     bool   `yaml:"isAutoAck" json:"isAutoAck"`
	MsgDurable    bool   `yaml:"msgDurable" json:"msgDurable"`
	NoLocal       bool   `yaml:"noLocal" json:"noLocal"`
	NoWait        bool   `yaml:"noWait" json:"noWait"`
	PrefetchCount int    `yaml:"prefetchCount" json:"prefetchCount"`
	PrefetchSize  int    `yaml:"prefetchSize" json:"prefetchSize"`
}

type DoingOrder struct {
	ConsumerNum              int                    `yaml:"consumerNum" json:"consumerNum"`
	ConsumerOption           ConsumerOption         `yaml:"consumerOption" json:"consumerOption"`
	DeadKey                  string                 `yaml:"deadKey" json:"deadKey"`
	DeadQueueBindOption      DeadQueueBindOption    `yaml:"deadQueueBindOption" json:"deadQueueBindOption"`
	DeadQueueDeclareOption   DeadQueueDeclareOption `yaml:"deadQueueDeclareOption" json:"deadQueueDeclareOption"`
	DeadQueueName            string                 `yaml:"deadQueueName" json:"deadQueueName"`
	Enable                   bool                   `yaml:"enable" json:"enable"`
	ErrKey                   string                 `yaml:"errKey" json:"errKey"`
	ErrQueueBindOption       DeadQueueBindOption    `yaml:"errQueueBindOption" json:"errQueueBindOption"`
	ErrQueueDeclareOption    ErrQueueDeclareOption  `yaml:"errQueueDeclareOption" json:"errQueueDeclareOption"`
	ErrQueueName             string                 `yaml:"errQueueName" json:"errQueueName"`
	ExchangeDeclareOptions   ExchangeDeclareOptions `yaml:"exchangeDeclareOptions" json:"exchangeDeclareOptions"`
	ExchangeName             string                 `yaml:"exchangeName" json:"exchangeName"`
	NormalKey                string                 `yaml:"normalKey" json:"normalKey"`
	NormalQueueBindOption    DeadQueueBindOption    `yaml:"normalQueueBindOption" json:"normalQueueBindOption"`
	NormalQueueDeclareOption ErrQueueDeclareOption  `yaml:"normalQueueDeclareOption" json:"normalQueueDeclareOption"`
	NormalQueueName          string                 `yaml:"normalQueueName" json:"normalQueueName"`
	QueueType                string                 `yaml:"queueType" json:"queueType"`
}

type NacosServer struct {
	ContextPath string `yaml:"contextPath" json:"contextPath"`
	IPAddr      string `yaml:"ipAddr" json:"ipAddr"`
	Port        int    `yaml:"port" json:"port"`
	Scheme      string `yaml:"scheme" json:"scheme"`
}

type LimitRules struct {
	ControlBehavior        string  `yaml:"controlBehavior" json:"controlBehavior"`
	Resource               string  `yaml:"resource" json:"resource"`
	StatIntervalInMs       int     `yaml:"statIntervalInMs" json:"statIntervalInMs"`
	Threshold              float64 `yaml:"threshold" json:"threshold"`
	TokenCalculateStrategy string  `yaml:"tokenCalculateStrategy" json:"tokenCalculateStrategy"`
}

type Redis struct {
	DialTimeout  int    `yaml:"dialTimeout" json:"dialTimeout"`
	Dsn          string `yaml:"dsn" json:"dsn"`
	IdleTimeout  int    `yaml:"idleTimeout" json:"idleTimeout"`
	MaxConnAge   int    `yaml:"maxConnAge" json:"maxConnAge"`
	MinIdleConns int    `yaml:"minIdleConns" json:"minIdleConns"`
	PoolSize     int    `yaml:"poolSize" json:"poolSize"`
	PoolTimeout  int    `yaml:"poolTimeout" json:"poolTimeout"`
	ReadTimeout  int    `yaml:"readTimeout" json:"readTimeout"`
	WriteTimeout int    `yaml:"writeTimeout" json:"writeTimeout"`
}

type Pool struct {
	DialTimeout       int    `yaml:"dialTimeout" json:"dialTimeout"`
	HealthCheckPeriod int    `yaml:"healthCheckPeriod" json:"healthCheckPeriod"`
	Heartbeat         int    `yaml:"heartbeat" json:"heartbeat"`
	InitialCap        int    `yaml:"initialCap" json:"initialCap"`
	MaxCap            int    `yaml:"maxCap" json:"maxCap"`
	MaxIdle           int    `yaml:"maxIdle" json:"maxIdle"`
	ReconnectTime     int    `yaml:"reconnectTime" json:"reconnectTime"`
	StatsLogOpen      bool   `yaml:"statsLogOpen" json:"statsLogOpen"`
	URL               string `yaml:"url" json:"url"`
}

type Websocket struct {
	Distributed Distributed `yaml:"distributed" json:"distributed"`
	Heartbeat   Heartbeat   `yaml:"heartbeat" json:"heartbeat"`
	Limit       Limit       `yaml:"limit" json:"limit"`
	Queue       Queue       `yaml:"queue" json:"queue"`
	Sso         Sso         `yaml:"sso" json:"sso"`
	Upgrade     Upgrade     `yaml:"upgrade" json:"upgrade"`
}

type Rabbitmq struct {
	DoingOrder DoingOrder `yaml:"DoingOrder" json:"DoingOrder"`
	Enable     bool       `yaml:"enable" json:"enable"`
	Pool       Pool       `yaml:"pool" json:"pool"`
}

type Database struct {
	Driver string `yaml:"driver" json:"driver"`
	Mysql  Mysql  `yaml:"mysql" json:"mysql"`
}

type Distributed struct {
	EnableDistributed bool   `yaml:"enableDistributed" json:"enableDistributed"`
	Exchange          string `yaml:"exchange" json:"exchange"`
	MaxConnections    int    `yaml:"maxConnections" json:"maxConnections"`
	PoolInitialCap    int    `yaml:"poolInitialCap" json:"poolInitialCap"`
	PoolMaxCap        int    `yaml:"poolMaxCap" json:"poolMaxCap"`
	RabbitmqURL       string `yaml:"rabbitmqURL" json:"rabbitmqURL"`
	ReceiveChanSize   int    `yaml:"receiveChanSize" json:"receiveChanSize"`
	WorkerPool        int    `yaml:"workerPool" json:"workerPool"`
}

type Heartbeat struct {
	EnableHeartbeat   bool `yaml:"enableHeartbeat" json:"enableHeartbeat"`
	HeartbeatInterval int  `yaml:"heartbeatInterval" json:"heartbeatInterval"`
	PingWriteWait     int  `yaml:"pingWriteWait" json:"pingWriteWait"`
	PongTimeout       int  `yaml:"pongTimeout" json:"pongTimeout"`
}

type Limit struct {
	EnableRateLimit bool `yaml:"enableRateLimit" json:"enableRateLimit"`
	MaxConnPerIP    int  `yaml:"maxConnPerIP" json:"maxConnPerIP"`
	RateLimitBurst  int  `yaml:"rateLimitBurst" json:"rateLimitBurst"`
	RateLimitRps    int  `yaml:"rateLimitRps" json:"rateLimitRps"`
}

type Sso struct {
	EnableSSO bool `yaml:"enableSSO" json:"enableSSO"`
}

type Grpc struct {
	EnableToken  bool         `yaml:"enableToken" json:"enableToken"`
	HTTPPort     int          `yaml:"httpPort" json:"httpPort"`
	Port         int          `yaml:"port" json:"port"`
	ServerSecure ServerSecure `yaml:"serverSecure" json:"serverSecure"`
}

type EtcdInfo struct {
	EtcdClient   EtcdClient   `yaml:"etcdClient" json:"etcdClient"`
	EtcdRegistry EtcdRegistry `yaml:"etcdRegistry" json:"etcdRegistry"`
	EtcdServer   EtcdServer   `yaml:"etcdServer" json:"etcdServer"`
}

type Jwt struct {
	Expire        int           `yaml:"expire" json:"expire"`
	IgnoreMethods IgnoreMethods `yaml:"ignoreMethods" json:"ignoreMethods"`
	Issuer        string        `yaml:"issuer" json:"issuer"`
	SigningKey    string        `yaml:"signingKey" json:"signingKey"`
	SigningMethod string        `yaml:"signingMethod" json:"signingMethod"`
}

type Routes struct {
	Filename      string `yaml:"filename" json:"filename"`
	Format        string `yaml:"format" json:"format"`
	IsAsync       bool   `yaml:"isAsync" json:"isAsync"`
	IsCompression bool   `yaml:"isCompression" json:"isCompression"`
	IsSaveDay     bool   `yaml:"isSaveDay" json:"isSaveDay"`
	MaxAge        int    `yaml:"maxAge" json:"maxAge"`
	MaxBackups    int    `yaml:"maxBackups" json:"maxBackups"`
	MaxSize       int    `yaml:"maxSize" json:"maxSize"`
	Module        string `yaml:"module" json:"module"`
}

type LogFileConfig struct {
	Filename      string `yaml:"filename" json:"filename"`
	IsCompression bool   `yaml:"isCompression" json:"isCompression"`
	IsNoPrint     bool   `yaml:"isNoPrint" json:"isNoPrint"`
	IsSaveDay     bool   `yaml:"isSaveDay" json:"isSaveDay"`
	MaxAge        int    `yaml:"maxAge" json:"maxAge"`
	MaxBackups    int    `yaml:"maxBackups" json:"maxBackups"`
	MaxSize       int    `yaml:"maxSize" json:"maxSize"`
}

type IgnoreMethods struct {
	Grpc []string `yaml:"grpc" json:"grpc"`
	HTTP []string `yaml:"http" json:"http"`
}

type SMTP struct {
	Host     string `yaml:"host" json:"host"`
	Password string `yaml:"password" json:"password"`
	Port     int    `yaml:"port" json:"port"`
	Username string `yaml:"username" json:"username"`
}

type HTTP struct {
	IdleTimeout       int `yaml:"idleTimeout" json:"idleTimeout"`
	Port              int `yaml:"port" json:"port"`
	ReadHeaderTimeout int `yaml:"readHeaderTimeout" json:"readHeaderTimeout"`
	ReadTimeout       int `yaml:"readTimeout" json:"readTimeout"`
	Timeout           int `yaml:"timeout" json:"timeout"`
	WriteTimeout      int `yaml:"writeTimeout" json:"writeTimeout"`
}

type Sign struct {
	IgnoreUrls      IgnoreMethods `yaml:"ignoreUrls" json:"ignoreUrls"`
	SignExpiredTime int           `yaml:"signExpiredTime" json:"signExpiredTime"`
	SignKey         string        `yaml:"signKey" json:"signKey"`
}

type BreakerRules struct {
	MinRequestAmount int     `yaml:"minRequestAmount" json:"minRequestAmount"`
	Resource         string  `yaml:"resource" json:"resource"`
	RetryTimeoutMs   int     `yaml:"retryTimeoutMs" json:"retryTimeoutMs"`
	StatIntervalMs   int     `yaml:"statIntervalMs" json:"statIntervalMs"`
	Strategy         string  `yaml:"strategy" json:"strategy"`
	Threshold        float64 `yaml:"threshold" json:"threshold"`
}

type NacosInfo struct {
	NacosClient   NacosClient   `yaml:"nacosClient" json:"nacosClient"`
	NacosRegistry NacosRegistry `yaml:"nacosRegistry" json:"nacosRegistry"`
	NacosServer   NacosServer   `yaml:"nacosServer" json:"nacosServer"`
}

type NacosClient struct {
	NamespaceID string `yaml:"namespaceID" json:"namespaceID"`
	Password    string `yaml:"password" json:"password"`
	TimeoutMs   int    `yaml:"timeoutMs" json:"timeoutMs"`
	Username    string `yaml:"username" json:"username"`
}

type DeadQueueBindOption struct {
	NoWait bool `yaml:"noWait" json:"noWait"`
}

type Queue struct {
	ReadLimit      int `yaml:"readLimit" json:"readLimit"`
	ReadQueueSize  int `yaml:"readQueueSize" json:"readQueueSize"`
	ReadTimeout    int `yaml:"readTimeout" json:"readTimeout"`
	WriteLimit     int `yaml:"writeLimit" json:"writeLimit"`
	WriteMsgType   int `yaml:"writeMsgType" json:"writeMsgType"`
	WriteQueueSize int `yaml:"writeQueueSize" json:"writeQueueSize"`
	WriteTimeout   int `yaml:"writeTimeout" json:"writeTimeout"`
}

type Args struct {
	XMessageTTL int `yaml:"xMessageTtl" json:"xMessageTtl"`
}