// code generated by https://github.com/18721889353/sunshine

package config

import (
	"github.com/18721889353/sunshine/pkg/conf"
)

var config *Config

func Init(configFile string, fs ...func()) error {
	config = &Config{}
	return conf.Parse(configFile, config, fs...)
}

func Show(hiddenFields ...string) string {
	return conf.Show(config, hiddenFields...)
}

func Get() *Config {
	if config == nil {
		panic("config is nil, please call config.Init() first")
	}
	return config
}

func Set(conf *Config) {
	config = conf
}

type Config struct {
	App           App           `yaml:"app" json:"app"`
	Database      Database      `yaml:"database" json:"database"`
	Elasticsearch Elasticsearch `yaml:"elasticsearch" json:"elasticsearch"`
	Etcd          Etcd          `yaml:"etcd" json:"etcd"`
	Grpc          Grpc          `yaml:"grpc" json:"grpc"`
	GrpcClient    []GrpcClient  `yaml:"grpcClient" json:"grpcClient"`
	HTTP          HTTP          `yaml:"http" json:"http"`
	Jaeger        Jaeger        `yaml:"jaeger" json:"jaeger"`
	Jwt           Jwt           `yaml:"jwt" json:"jwt"`
	Logger        Logger        `yaml:"logger" json:"logger"`
	Rabbitmq      Rabbitmq      `yaml:"rabbitmq" json:"rabbitmq"`
	Redis         Redis         `yaml:"redis" json:"redis"`
	Sentinel      Sentinel      `yaml:"sentinel" json:"sentinel"`
	Sign          Sign          `yaml:"sign" json:"sign"`
}

type Elasticsearch struct {
	Addresses             []string `yaml:"addresses" json:"addresses"`
	APIKey                string   `yaml:"apiKey" json:"apiKey"`
	ConnectionKeepAlive   int      `yaml:"connection_keep_alive" json:"connection_keep_alive"`
	ConnectionTimeout     int      `yaml:"connection_timeout" json:"connection_timeout"`
	EnableHealthCheck     bool     `yaml:"enable_health_check" json:"enable_health_check"`
	EnablePingCheck       bool     `yaml:"enable_ping_check" json:"enable_ping_check"`
	ExpectContinueTimeout int      `yaml:"expect_continue_timeout" json:"expect_continue_timeout"`
	IdleConnTimeout       int      `yaml:"idle_conn_timeout" json:"idle_conn_timeout"`
	IsOpen                bool     `yaml:"isOpen" json:"isOpen"`
	MaxConnsPerHost       int      `yaml:"max_conns_per_host" json:"max_conns_per_host"`
	MaxIdleConns          int      `yaml:"max_idle_conns" json:"max_idle_conns"`
	MaxIdleConnsPerHost   int      `yaml:"max_idle_conns_per_host" json:"max_idle_conns_per_host"`
	MaxRetries            int      `yaml:"max_retries" json:"max_retries"`
	Password              string   `yaml:"password" json:"password"`
	ResponseHeaderTimeout int      `yaml:"response_header_timeout" json:"response_header_timeout"`
	RetryBackoff          int      `yaml:"retry_backoff" json:"retry_backoff"`
	RetryOnStatus         []int    `yaml:"retry_on_status" json:"retry_on_status"`
	Timeout               int      `yaml:"timeout" json:"timeout"`
	TLSHandshakeTimeout   int      `yaml:"tls_handshake_timeout" json:"tls_handshake_timeout"`
	Username              string   `yaml:"username" json:"username"`
}

type Etcd struct {
	Addrs []string `yaml:"addrs" json:"addrs"`
}

type Jaeger struct {
	AgentHost string `yaml:"agentHost" json:"agentHost"`
	AgentPort int    `yaml:"agentPort" json:"agentPort"`
}

type Pool struct {
	AntsCap           int    `yaml:"antsCap" json:"antsCap"`
	DialTimeout       int    `yaml:"dialTimeout" json:"dialTimeout"`
	HealthCheckPeriod int    `yaml:"healthCheckPeriod" json:"healthCheckPeriod"`
	Heartbeat         int    `yaml:"heartbeat" json:"heartbeat"`
	InitialCap        int    `yaml:"initialCap" json:"initialCap"`
	MaxCap            int    `yaml:"maxCap" json:"maxCap"`
	MaxIdle           int    `yaml:"maxIdle" json:"maxIdle"`
	ReconnectTime     int    `yaml:"reconnectTime" json:"reconnectTime"`
	URL               string `yaml:"url" json:"url"`
}

type ClientToken struct {
	AppID  string `yaml:"appID" json:"appID"`
	AppKey string `yaml:"appKey" json:"appKey"`
	Enable bool   `yaml:"enable" json:"enable"`
}

type DeadQueueDeclareOption struct {
	Args       Args `yaml:"args" json:"args"`
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Exclusive  bool `yaml:"exclusive" json:"exclusive"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type NormalQueueDeclareOption struct {
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Exclusive  bool `yaml:"exclusive" json:"exclusive"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type ExchangeDeclareOptions struct {
	AutoDelete bool `yaml:"autoDelete" json:"autoDelete"`
	Durable    bool `yaml:"durable" json:"durable"`
	Internal   bool `yaml:"internal" json:"internal"`
	NoWait     bool `yaml:"noWait" json:"noWait"`
}

type ClientSecure struct {
	CaFile     string `yaml:"caFile" json:"caFile"`
	CertFile   string `yaml:"certFile" json:"certFile"`
	KeyFile    string `yaml:"keyFile" json:"keyFile"`
	ServerName string `yaml:"serverName" json:"serverName"`
	Type       string `yaml:"type" json:"type"`
}

type ServerSecure struct {
	CaFile   string `yaml:"caFile" json:"caFile"`
	CertFile string `yaml:"certFile" json:"certFile"`
	KeyFile  string `yaml:"keyFile" json:"keyFile"`
	Type     string `yaml:"type" json:"type"`
}

type App struct {
	CacheType             string  `yaml:"cacheType" json:"cacheType"`
	EnableCircuitBreaker  bool    `yaml:"enableCircuitBreaker" json:"enableCircuitBreaker"`
	EnableHTTPProfile     bool    `yaml:"enableHTTPProfile" json:"enableHTTPProfile"`
	EnableLimit           bool    `yaml:"enableLimit" json:"enableLimit"`
	EnableMetrics         bool    `yaml:"enableMetrics" json:"enableMetrics"`
	EnableStat            bool    `yaml:"enableStat" json:"enableStat"`
	EnableTrace           bool    `yaml:"enableTrace" json:"enableTrace"`
	Env                   string  `yaml:"env" json:"env"`
	Host                  string  `yaml:"host" json:"host"`
	MachineID             int     `yaml:"machineId" json:"machineId"`
	Name                  string  `yaml:"name" json:"name"`
	OpenCron              bool    `yaml:"openCron" json:"openCron"`
	OpenHTTP              bool    `yaml:"openHttp" json:"openHttp"`
	OpenJwt               bool    `yaml:"openJwt" json:"openJwt"`
	OpenRabbitmqConsumer  bool    `yaml:"openRabbitmqConsumer" json:"openRabbitmqConsumer"`
	OpenSign              bool    `yaml:"openSign" json:"openSign"`
	OpenXSS               bool    `yaml:"openXSS" json:"openXSS"`
	RegistryDiscoveryType string  `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	TracingSamplingRate   float64 `yaml:"tracingSamplingRate" json:"tracingSamplingRate"`
	Version               string  `yaml:"version" json:"version"`
}

type GrpcClient struct {
	ClientSecure          ClientSecure `yaml:"clientSecure" json:"clientSecure"`
	ClientToken           ClientToken  `yaml:"clientToken" json:"clientToken"`
	EnableLoadBalance     bool         `yaml:"enableLoadBalance" json:"enableLoadBalance"`
	Host                  string       `yaml:"host" json:"host"`
	Name                  string       `yaml:"name" json:"name"`
	Port                  int          `yaml:"port" json:"port"`
	RegistryDiscoveryType string       `yaml:"registryDiscoveryType" json:"registryDiscoveryType"`
	Timeout               int          `yaml:"timeout" json:"timeout"`
}

type Sqlite struct {
	ConnMaxLifetime int    `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	DBFile          string `yaml:"dbFile" json:"dbFile"`
	EnableLog       bool   `yaml:"enableLog" json:"enableLog"`
	MaxIdleConns    int    `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxOpenConns    int    `yaml:"maxOpenConns" json:"maxOpenConns"`
}

type Mysql struct {
	ConnMaxLifetime int    `yaml:"connMaxLifetime" json:"connMaxLifetime"`
	Dsn             string `yaml:"dsn" json:"dsn"`
	EnableLog       bool   `yaml:"enableLog" json:"enableLog"`
	MaxIdleConns    int    `yaml:"maxIdleConns" json:"maxIdleConns"`
	MaxOpenConns    int    `yaml:"maxOpenConns" json:"maxOpenConns"`
}

type ConsumerOption struct {
	Consumer      string `yaml:"consumer" json:"consumer"`
	Exclusive     bool   `yaml:"exclusive" json:"exclusive"`
	Global        bool   `yaml:"global" json:"global"`
	IsAutoAck     bool   `yaml:"isAutoAck" json:"isAutoAck"`
	MsgDurable    bool   `yaml:"msgDurable" json:"msgDurable"`
	NoLocal       bool   `yaml:"noLocal" json:"noLocal"`
	NoWait        bool   `yaml:"noWait" json:"noWait"`
	PrefetchCount int    `yaml:"prefetchCount" json:"prefetchCount"`
	PrefetchSize  int    `yaml:"prefetchSize" json:"prefetchSize"`
}

type TestOrder struct {
	ConsumerNum       int               `yaml:"consumerNum" json:"consumerNum"`
	DeadLetterOptions DeadLetterOptions `yaml:"deadLetterOptions" json:"deadLetterOptions"`
	DeadQueueName     string            `yaml:"deadQueueName" json:"deadQueueName"`
	Enable            bool              `yaml:"enable" json:"enable"`
	ExchangeName      string            `yaml:"exchangeName" json:"exchangeName"`
	NormalQueueName   string            `yaml:"normalQueueName" json:"normalQueueName"`
	QueueType         string            `yaml:"queueType" json:"queueType"`
}

type DeadLetterOptions struct {
	ConsumerOption           ConsumerOption           `yaml:"consumerOption" json:"consumerOption"`
	DeadQueueBindOption      DeadQueueBindOption      `yaml:"deadQueueBindOption" json:"deadQueueBindOption"`
	DeadQueueDeclareOption   DeadQueueDeclareOption   `yaml:"deadQueueDeclareOption" json:"deadQueueDeclareOption"`
	ExchangeDeclareOptions   ExchangeDeclareOptions   `yaml:"exchangeDeclareOptions" json:"exchangeDeclareOptions"`
	NormalQueueBindOption    DeadQueueBindOption      `yaml:"normalQueueBindOption" json:"normalQueueBindOption"`
	NormalQueueDeclareOption NormalQueueDeclareOption `yaml:"normalQueueDeclareOption" json:"normalQueueDeclareOption"`
}

type Redis struct {
	DialTimeout  int    `yaml:"dialTimeout" json:"dialTimeout"`
	Dsn          string `yaml:"dsn" json:"dsn"`
	PoolSize     int    `yaml:"poolSize" json:"poolSize"`
	ReadTimeout  int    `yaml:"readTimeout" json:"readTimeout"`
	WriteTimeout int    `yaml:"writeTimeout" json:"writeTimeout"`
}

type Database struct {
	Driver     string  `yaml:"driver" json:"driver"`
	Mongodb    Mongodb `yaml:"mongodb" json:"mongodb"`
	Mysql      Mysql   `yaml:"mysql" json:"mysql"`
	Postgresql Mysql   `yaml:"postgresql" json:"postgresql"`
	Sqlite     Sqlite  `yaml:"sqlite" json:"sqlite"`
}

type Mongodb struct {
	Dsn string `yaml:"dsn" json:"dsn"`
}

type Rabbitmq struct {
	Enable    bool      `yaml:"enable" json:"enable"`
	Pool      Pool      `yaml:"pool" json:"pool"`
	TestOrder TestOrder `yaml:"testOrder" json:"testOrder"`
}

type Grpc struct {
	EnableToken  bool         `yaml:"enableToken" json:"enableToken"`
	HTTPPort     int          `yaml:"httpPort" json:"httpPort"`
	Port         int          `yaml:"port" json:"port"`
	ServerSecure ServerSecure `yaml:"serverSecure" json:"serverSecure"`
}

type Jwt struct {
	Expire        int           `yaml:"expire" json:"expire"`
	IgnoreMethods IgnoreMethods `yaml:"ignoreMethods" json:"ignoreMethods"`
	Issuer        string        `yaml:"issuer" json:"issuer"`
	SigningKey    string        `yaml:"signingKey" json:"signingKey"`
	SigningMethod string        `yaml:"signingMethod" json:"signingMethod"`
}

type LogFileConfig struct {
	Filename      string `yaml:"filename" json:"filename"`
	IsCompression bool   `yaml:"isCompression" json:"isCompression"`
	IsNoPrint     bool   `yaml:"isNoPrint" json:"isNoPrint"`
	IsSaveDay     bool   `yaml:"isSaveDay" json:"isSaveDay"`
	MaxAge        int    `yaml:"maxAge" json:"maxAge"`
	MaxBackups    int    `yaml:"maxBackups" json:"maxBackups"`
	MaxSize       int    `yaml:"maxSize" json:"maxSize"`
}

type Logger struct {
	Format        string        `yaml:"format" json:"format"`
	IsSave        bool          `yaml:"isSave" json:"isSave"`
	Level         string        `yaml:"level" json:"level"`
	LogFileConfig LogFileConfig `yaml:"logFileConfig" json:"logFileConfig"`
	MaxLen        int           `yaml:"maxLen" json:"maxLen"`
}

type IgnoreMethods struct {
	Grpc []string `yaml:"grpc" json:"grpc"`
	HTTP []string `yaml:"http" json:"http"`
}

type Sign struct {
	IgnoreUrls      IgnoreMethods `yaml:"ignoreUrls" json:"ignoreUrls"`
	SignExpiredTime int           `yaml:"signExpiredTime" json:"signExpiredTime"`
	SignKey         string        `yaml:"signKey" json:"signKey"`
}

type DeadQueueBindOption struct {
	NoWait bool `yaml:"noWait" json:"noWait"`
}

type HTTP struct {
	Port    int `yaml:"port" json:"port"`
	Timeout int `yaml:"timeout" json:"timeout"`
}

type Rules struct {
	Resource         string  `yaml:"resource" json:"resource"`
	StatIntervalInMs int     `yaml:"statIntervalInMs" json:"statIntervalInMs"`
	Threshold        float64 `yaml:"threshold" json:"threshold"`
}

type Sentinel struct {
	Rules []Rules `yaml:"rules" json:"rules"`
}

type Args struct {
	X_message_ttl int `yaml:"x-message-ttl" json:"x-message-ttl"`
}