version: "3.7"

services:
  sunshine:
    image: 18721889353/sunshine:latest
    container_name: sunshine
    restart: always
    # address of the front-end page requesting the sunshine service
    command: ["-l","-a","http://192.168.3.37:24631"]
    ports:
      - "24631:24631"
